// generated source. do not edit.
#![allow(non_upper_case_globals, unused_macros, unused_imports)]
use crate::low::macros::*;

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT-0

// ----------------------------------------------------------------------------
// Square, z := x^2
// Input x[16]; output z[32]; temporary buffer t[>=24]
//
//    extern void bignum_ksqr_16_32
//     (uint64_t z[static 32], uint64_t x[static 16], uint64_t t[static 24]);
//
// In this x86 code the final temporary space argument t is unused, but
// it is retained in the prototype above for API consistency with ARM.
//
// Standard x86-64 ABI: RDI = z, RSI = x, RDX = t
// Microsoft x64 ABI:   RCX = z, RDX = x, R8 = t
// ----------------------------------------------------------------------------

/// Square, z := x^2
///
/// Input x[16]; output z[32]; temporary buffer t[>=24]
///
/// In this x86 code the final temporary space argument t is unused, but
/// it is retained in the prototype above for API consistency with ARM.
pub(crate) fn bignum_ksqr_16_32(z: &mut [u64], x: &[u64], t: &mut [u64; 24]) {
    debug_assert!(z.len() == 32);
    debug_assert!(x.len() == 16);
    // SAFETY: inline assembly. see [crate::low::inline_assembly_safety] for safety info.
    unsafe {
        core::arch::asm!(

        Q!("    push            " "rbp"),
        Q!("    push            " "r12"),
        Q!("    push            " "r13"),
        Q!("    push            " "r14"),
        Q!("    push            " "r15"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi]"),
        Q!("    mulx            " "rax, r9, QWORD PTR [rsi + 0x8]"),
        Q!("    mov             " "QWORD PTR [rdi + 0x8], r9"),
        Q!("    mulx            " "rcx, r10, QWORD PTR [rsi + 0x10]"),
        Q!("    adcx            " "r10, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0x10], r10"),
        Q!("    mulx            " "rax, r11, QWORD PTR [rsi + 0x18]"),
        Q!("    adcx            " "r11, rcx"),
        Q!("    mulx            " "rcx, r12, QWORD PTR [rsi + 0x20]"),
        Q!("    adcx            " "r12, rax"),
        Q!("    mulx            " "rax, r13, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r13, rcx"),
        Q!("    mulx            " "rcx, r14, QWORD PTR [rsi + 0x30]"),
        Q!("    adcx            " "r14, rax"),
        Q!("    mulx            " "r8, r15, QWORD PTR [rsi + 0x38]"),
        Q!("    adcx            " "r15, rcx"),
        Q!("    adcx            " "r8, rbp"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x8]"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x10]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x18], r11"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x18]"),
        Q!("    adcx            " "r12, rax"),
        Q!("    adox            " "r13, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x20], r12"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x20]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r14, rax"),
        Q!("    adox            " "r15, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x30]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rcx"),
        Q!("    mulx            " "r9, rax, QWORD PTR [rsi + 0x38]"),
        Q!("    adcx            " "r8, rax"),
        Q!("    adox            " "r9, rbp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x20]"),
        Q!("    mulx            " "r10, rax, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rbp"),
        Q!("    adcx            " "r10, rbp"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x10]"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x18]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x28], r13"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x20]"),
        Q!("    adcx            " "r14, rax"),
        Q!("    adox            " "r15, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x30], r14"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x30]"),
        Q!("    adcx            " "r8, rax"),
        Q!("    adox            " "r9, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x38]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rcx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x30]"),
        Q!("    mulx            " "r11, rax, QWORD PTR [rsi + 0x20]"),
        Q!("    adcx            " "r10, rax"),
        Q!("    adox            " "r11, rbp"),
        Q!("    mulx            " "r12, rax, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rbp"),
        Q!("    adcx            " "r12, rbp"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x18]"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x20]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x38], r15"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r8, rax"),
        Q!("    adox            " "r9, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x30]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x38]"),
        Q!("    adcx            " "r10, rax"),
        Q!("    adox            " "r11, rcx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x38]"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x20]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rcx"),
        Q!("    mulx            " "r13, rax, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r12, rax"),
        Q!("    adox            " "r13, rbp"),
        Q!("    mulx            " "r14, rax, QWORD PTR [rsi + 0x30]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rbp"),
        Q!("    adcx            " "r14, rbp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x40]"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi]"),
        Q!("    adcx            " "r8, rax"),
        Q!("    adox            " "r9, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x40], r8"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x8]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x10]"),
        Q!("    adcx            " "r10, rax"),
        Q!("    adox            " "r11, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x18]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x20]"),
        Q!("    adcx            " "r12, rax"),
        Q!("    adox            " "r13, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rcx"),
        Q!("    mulx            " "r15, rax, QWORD PTR [rsi + 0x30]"),
        Q!("    adcx            " "r14, rax"),
        Q!("    adox            " "r15, rbp"),
        Q!("    mulx            " "r8, rax, QWORD PTR [rsi + 0x38]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rbp"),
        Q!("    adcx            " "r8, rbp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x48]"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x48], r9"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x8]"),
        Q!("    adcx            " "r10, rax"),
        Q!("    adox            " "r11, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x10]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x18]"),
        Q!("    adcx            " "r12, rax"),
        Q!("    adox            " "r13, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x20]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r14, rax"),
        Q!("    adox            " "r15, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x30]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rcx"),
        Q!("    mulx            " "r9, rax, QWORD PTR [rsi + 0x38]"),
        Q!("    adcx            " "r8, rax"),
        Q!("    adox            " "r9, rbp"),
        Q!("    adcx            " "r9, rbp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x50]"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi]"),
        Q!("    adcx            " "r10, rax"),
        Q!("    adox            " "r11, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x50], r10"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x8]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x10]"),
        Q!("    adcx            " "r12, rax"),
        Q!("    adox            " "r13, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x18]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x20]"),
        Q!("    adcx            " "r14, rax"),
        Q!("    adox            " "r15, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x30]"),
        Q!("    adcx            " "r8, rax"),
        Q!("    adox            " "r9, rcx"),
        Q!("    mulx            " "r10, rax, QWORD PTR [rsi + 0x38]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rbp"),
        Q!("    adcx            " "r10, rbp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x58]"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x58], r11"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x8]"),
        Q!("    adcx            " "r12, rax"),
        Q!("    adox            " "r13, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x10]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x18]"),
        Q!("    adcx            " "r14, rax"),
        Q!("    adox            " "r15, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x20]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r8, rax"),
        Q!("    adox            " "r9, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x30]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rcx"),
        Q!("    mulx            " "r11, rax, QWORD PTR [rsi + 0x38]"),
        Q!("    adcx            " "r10, rax"),
        Q!("    adox            " "r11, rbp"),
        Q!("    adcx            " "r11, rbp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x60]"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi]"),
        Q!("    adcx            " "r12, rax"),
        Q!("    adox            " "r13, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x60], r12"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x8]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x10]"),
        Q!("    adcx            " "r14, rax"),
        Q!("    adox            " "r15, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x18]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x20]"),
        Q!("    adcx            " "r8, rax"),
        Q!("    adox            " "r9, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x30]"),
        Q!("    adcx            " "r10, rax"),
        Q!("    adox            " "r11, rcx"),
        Q!("    mulx            " "r12, rax, QWORD PTR [rsi + 0x38]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rbp"),
        Q!("    adcx            " "r12, rbp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x68]"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x68], r13"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x8]"),
        Q!("    adcx            " "r14, rax"),
        Q!("    adox            " "r15, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x10]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x18]"),
        Q!("    adcx            " "r8, rax"),
        Q!("    adox            " "r9, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x20]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r10, rax"),
        Q!("    adox            " "r11, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x30]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rcx"),
        Q!("    mulx            " "r13, rax, QWORD PTR [rsi + 0x38]"),
        Q!("    adcx            " "r12, rax"),
        Q!("    adox            " "r13, rbp"),
        Q!("    adcx            " "r13, rbp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x70]"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi]"),
        Q!("    adcx            " "r14, rax"),
        Q!("    adox            " "r15, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x70], r14"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x8]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x10]"),
        Q!("    adcx            " "r8, rax"),
        Q!("    adox            " "r9, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x18]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x20]"),
        Q!("    adcx            " "r10, rax"),
        Q!("    adox            " "r11, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x30]"),
        Q!("    adcx            " "r12, rax"),
        Q!("    adox            " "r13, rcx"),
        Q!("    mulx            " "r14, rax, QWORD PTR [rsi + 0x38]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rbp"),
        Q!("    adcx            " "r14, rbp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x78]"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x78], r15"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x8]"),
        Q!("    adcx            " "r8, rax"),
        Q!("    adox            " "r9, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x10]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x18]"),
        Q!("    adcx            " "r10, rax"),
        Q!("    adox            " "r11, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x20]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x28]"),
        Q!("    adcx            " "r12, rax"),
        Q!("    adox            " "r13, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x30]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rcx"),
        Q!("    mulx            " "r15, rax, QWORD PTR [rsi + 0x38]"),
        Q!("    adcx            " "r14, rax"),
        Q!("    adox            " "r15, rbp"),
        Q!("    adcx            " "r15, rbp"),
        Q!("    mov             " "QWORD PTR [rdi + 0x80], r8"),
        Q!("    mov             " "QWORD PTR [rdi + 0x88], r9"),
        Q!("    mov             " "QWORD PTR [rdi + 0x90], r10"),
        Q!("    mov             " "QWORD PTR [rdi + 0x98], r11"),
        Q!("    mov             " "QWORD PTR [rdi + 0xa0], r12"),
        Q!("    mov             " "QWORD PTR [rdi + 0xa8], r13"),
        Q!("    mov             " "QWORD PTR [rdi + 0xb0], r14"),
        Q!("    mov             " "QWORD PTR [rdi + 0xb8], r15"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mov             " "r9, QWORD PTR [rdi + 0x88]"),
        Q!("    mov             " "r10, QWORD PTR [rdi + 0x90]"),
        Q!("    mov             " "r11, QWORD PTR [rdi + 0x98]"),
        Q!("    mov             " "r12, QWORD PTR [rdi + 0xa0]"),
        Q!("    mov             " "r13, QWORD PTR [rdi + 0xa8]"),
        Q!("    mov             " "r14, QWORD PTR [rdi + 0xb0]"),
        Q!("    mov             " "r15, QWORD PTR [rdi + 0xb8]"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x40]"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x48]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x88], r9"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x50]"),
        Q!("    adcx            " "r10, rax"),
        Q!("    adox            " "r11, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x90], r10"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x58]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x60]"),
        Q!("    adcx            " "r12, rax"),
        Q!("    adox            " "r13, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x68]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x70]"),
        Q!("    adcx            " "r14, rax"),
        Q!("    adox            " "r15, rcx"),
        Q!("    mulx            " "r8, rax, QWORD PTR [rsi + 0x78]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rbp"),
        Q!("    adcx            " "r8, rbp"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x48]"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x50]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x98], r11"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x58]"),
        Q!("    adcx            " "r12, rax"),
        Q!("    adox            " "r13, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0xa0], r12"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x60]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x68]"),
        Q!("    adcx            " "r14, rax"),
        Q!("    adox            " "r15, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x70]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rcx"),
        Q!("    mulx            " "r9, rax, QWORD PTR [rsi + 0x78]"),
        Q!("    adcx            " "r8, rax"),
        Q!("    adox            " "r9, rbp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x60]"),
        Q!("    mulx            " "r10, rax, QWORD PTR [rsi + 0x68]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rbp"),
        Q!("    adcx            " "r10, rbp"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x50]"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x58]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0xa8], r13"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x60]"),
        Q!("    adcx            " "r14, rax"),
        Q!("    adox            " "r15, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0xb0], r14"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x68]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x70]"),
        Q!("    adcx            " "r8, rax"),
        Q!("    adox            " "r9, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x78]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rcx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x70]"),
        Q!("    mulx            " "r11, rax, QWORD PTR [rsi + 0x60]"),
        Q!("    adcx            " "r10, rax"),
        Q!("    adox            " "r11, rbp"),
        Q!("    mulx            " "r12, rax, QWORD PTR [rsi + 0x68]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rbp"),
        Q!("    adcx            " "r12, rbp"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x58]"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x60]"),
        Q!("    adcx            " "r15, rax"),
        Q!("    adox            " "r8, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0xb8], r15"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x68]"),
        Q!("    adcx            " "r8, rax"),
        Q!("    adox            " "r9, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x70]"),
        Q!("    adcx            " "r9, rax"),
        Q!("    adox            " "r10, rcx"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x78]"),
        Q!("    adcx            " "r10, rax"),
        Q!("    adox            " "r11, rcx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x78]"),
        Q!("    mulx            " "rcx, rax, QWORD PTR [rsi + 0x60]"),
        Q!("    adcx            " "r11, rax"),
        Q!("    adox            " "r12, rcx"),
        Q!("    mulx            " "r13, rax, QWORD PTR [rsi + 0x68]"),
        Q!("    adcx            " "r12, rax"),
        Q!("    adox            " "r13, rbp"),
        Q!("    mulx            " "r14, rax, QWORD PTR [rsi + 0x70]"),
        Q!("    adcx            " "r13, rax"),
        Q!("    adox            " "r14, rbp"),
        Q!("    adcx            " "r14, rbp"),
        Q!("    mov             " "QWORD PTR [rdi + 0xc0], r8"),
        Q!("    mov             " "QWORD PTR [rdi + 0xc8], r9"),
        Q!("    mov             " "QWORD PTR [rdi + 0xd0], r10"),
        Q!("    mov             " "QWORD PTR [rdi + 0xd8], r11"),
        Q!("    mov             " "QWORD PTR [rdi + 0xe0], r12"),
        Q!("    mov             " "QWORD PTR [rdi + 0xe8], r13"),
        Q!("    mov             " "QWORD PTR [rdi + 0xf0], r14"),
        Q!("    xor             " "ebp, ebp"),
        Q!("    mov             " "rdx, QWORD PTR [rsi]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "QWORD PTR [rdi], rax"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x8]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x8], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x8]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x10]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0x10], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x18]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x18], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x10]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x20]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0x20], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x28]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x28], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x18]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x30]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0x30], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x38]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x38], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x20]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x40]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0x40], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x48]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x48], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x28]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x50]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0x50], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x58]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x58], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x30]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x60]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0x60], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x68]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x68], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x38]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x70]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0x70], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x78]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x78], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x40]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x80]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0x80], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x88]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x88], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x48]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x90]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0x90], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0x98]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0x98], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x50]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0xa0]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0xa0], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0xa8]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0xa8], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x58]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0xb0]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0xb0], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0xb8]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0xb8], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x60]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0xc0]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0xc0], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0xc8]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0xc8], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x68]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0xd0]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0xd0], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0xd8]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0xd8], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x70]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0xe0]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0xe0], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0xe8]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rcx"),
        Q!("    mov             " "QWORD PTR [rdi + 0xe8], rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rsi + 0x78]"),
        Q!("    mulx            " "rcx, rax, rdx"),
        Q!("    mov             " "rdx, QWORD PTR [rdi + 0xf0]"),
        Q!("    adcx            " "rdx, rdx"),
        Q!("    adox            " "rdx, rax"),
        Q!("    mov             " "QWORD PTR [rdi + 0xf0], rdx"),
        Q!("    adcx            " "rcx, rbp"),
        Q!("    adox            " "rcx, rbp"),
        Q!("    mov             " "QWORD PTR [rdi + 0xf8], rcx"),
        Q!("    pop             " "r15"),
        Q!("    pop             " "r14"),
        Q!("    pop             " "r13"),
        Q!("    pop             " "r12"),
        Q!("    pop             " "rbp"),
        inout("rdi") z.as_mut_ptr() => _,
        inout("rsi") x.as_ptr() => _,
        inout("rdx") t.as_mut_ptr() => _,
        // clobbers
        out("r10") _,
        out("r11") _,
        out("r12") _,
        out("r13") _,
        out("r14") _,
        out("r15") _,
        out("r8") _,
        out("r9") _,
        out("rax") _,
        out("rcx") _,
            )
    };
}
