// generated source. do not edit.
#![allow(non_upper_case_globals, unused_macros, unused_imports)]
use crate::low::macros::*;

// Copyright (c) 2024 The mlkem-native project authors
// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

// ----------------------------------------------------------------------------
// Scalar product of 3-element polynomial vectors in NTT domain, with mulcache
// Inputs a[768], b[768], bt[384] (signed 16-bit words); output r[256] (signed 16-bit words)
//
// The inputs a and b are considered as 3-element vectors of linear
// polynomials in the NTT domain (in Montgomery form), and the bt
// argument an analogous 3-element vector of mulcaches for the bi:
//
//   a0 = a[0..255], a1 = a[256..511], a2 = a[512..767]
//   b0 = b[0..255], b1 = b[256..511], b2 = b[512..767],
//   bt0 = bt[0..127], bt1 = bt[128..255], bt2 = bt[256..383]
//
// Scalar multiplication of those 3-element vectors is performed,
// with base multiplication in Fq[X]/(X^2-zeta^i'), with zeta^i'
// being a power of zeta = 17, with i bit-reversed as used for NTTs,
// making use of the mulcache for optimization.
//
// All input elements are assumed <= 2^12 and the bts are
// assumed to be as computed by mlkem_mulcache_compute.
//
// extern void mlkem_basemul_k3
//      (int16_t r[static 256],const int16_t a[static 768],
//       const int16_t b[static 768], const int16_t bt[static 384]);
//
// Standard x86-64 ABI: RDI = r, RSI = a, RDX = b, RCX = bt
// Microsoft x64 ABI:   RCX = r, RDX = a, R8 = b, R9 = bt
// ----------------------------------------------------------------------------

/// Scalar product of 3-element polynomial vectors in NTT domain, with mulcache
///
/// Inputs a[768], b[768], bt[384] (signed 16-bit words); output r[256] (signed 16-bit words)
///
/// The inputs a and b are considered as 3-element vectors of linear
/// polynomials in the NTT domain (in Montgomery form), and the bt
/// argument an analogous 3-element vector of mulcaches for the bi:
///
///   a0 = a[0..255], a1 = a[256..511], a2 = a[512..767]
///   b0 = b[0..255], b1 = b[256..511], b2 = b[512..767],
///   bt0 = bt[0..127], bt1 = bt[128..255], bt2 = bt[256..383]
///
/// Scalar multiplication of those 3-element vectors is performed,
/// with base multiplication in Fq[X]/(X^2-zeta^i'), with zeta^i'
/// being a power of zeta = 17, with i bit-reversed as used for NTTs,
/// making use of the mulcache for optimization.
///
/// All input elements are assumed <= 2^12 and the bts are
/// assumed to be as computed by mlkem_mulcache_compute.
pub(crate) fn mlkem_basemul_k3(
    r: &mut [i16; 256],
    a: &[i16; 768],
    b: &[i16; 768],
    bt: &[i16; 384],
) {
    // SAFETY: inline assembly. see [crate::low::inline_assembly_safety] for safety info.
    unsafe {
        core::arch::asm!(

        Q!("    endbr64         " ),

        Q!("    mov             " "eax, 0xd010d01"),
        Q!("    vmovd           " "xmm0, eax"),
        Q!("    vpbroadcastd    " "ymm0, xmm0"),
        Q!("    mov             " "eax, 0xf301f301"),
        Q!("    vmovd           " "xmm1, eax"),
        Q!("    vpbroadcastd    " "ymm1, xmm1"),
        Q!("    vmovdqa         " "ymm2, [rsi]"),
        Q!("    vmovdqa         " "ymm3, [32 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [rdx]"),
        Q!("    vmovdqa         " "ymm5, [32 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm13, ymm8"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[rdi], ymm7"),
        Q!("    vmovdqa         " "[32 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [64 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [96 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [64 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [96 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [32 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm13"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[64 + rdi], ymm7"),
        Q!("    vmovdqa         " "[96 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [128 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [160 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [128 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [160 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [64 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm13, ymm8"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[128 + rdi], ymm7"),
        Q!("    vmovdqa         " "[160 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [192 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [224 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [192 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [224 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [96 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm13"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[192 + rdi], ymm7"),
        Q!("    vmovdqa         " "[224 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [256 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [288 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [256 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [288 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [128 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm13, ymm8"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[256 + rdi], ymm7"),
        Q!("    vmovdqa         " "[288 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [320 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [352 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [320 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [352 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [160 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm13"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[320 + rdi], ymm7"),
        Q!("    vmovdqa         " "[352 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [384 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [416 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [384 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [416 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [192 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm13, ymm8"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[384 + rdi], ymm7"),
        Q!("    vmovdqa         " "[416 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [448 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [480 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [448 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [480 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [224 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm13"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[448 + rdi], ymm7"),
        Q!("    vmovdqa         " "[480 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [512 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [544 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [512 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [544 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [256 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm13, ymm8"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [rdi]"),
        Q!("    vmovdqa         " "ymm10, [32 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[rdi], ymm7"),
        Q!("    vmovdqa         " "[32 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [576 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [608 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [576 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [608 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [288 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm13"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [64 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [96 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[64 + rdi], ymm7"),
        Q!("    vmovdqa         " "[96 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [640 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [672 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [640 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [672 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [320 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm13, ymm8"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [128 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [160 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[128 + rdi], ymm7"),
        Q!("    vmovdqa         " "[160 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [704 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [736 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [704 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [736 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [352 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm13"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [192 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [224 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[192 + rdi], ymm7"),
        Q!("    vmovdqa         " "[224 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [768 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [800 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [768 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [800 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [384 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm13, ymm8"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [256 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [288 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[256 + rdi], ymm7"),
        Q!("    vmovdqa         " "[288 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [832 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [864 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [832 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [864 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [416 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm13"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [320 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [352 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[320 + rdi], ymm7"),
        Q!("    vmovdqa         " "[352 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [896 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [928 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [896 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [928 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [448 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm13, ymm8"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [384 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [416 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[384 + rdi], ymm7"),
        Q!("    vmovdqa         " "[416 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [960 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [992 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [960 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [992 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [480 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm13"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [448 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [480 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[448 + rdi], ymm7"),
        Q!("    vmovdqa         " "[480 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [1024 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [1056 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [1024 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [1056 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [512 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm13, ymm8"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [rdi]"),
        Q!("    vmovdqa         " "ymm10, [32 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[rdi], ymm7"),
        Q!("    vmovdqa         " "[32 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [1088 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [1120 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [1088 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [1120 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [544 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm13"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [64 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [96 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[64 + rdi], ymm7"),
        Q!("    vmovdqa         " "[96 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [1152 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [1184 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [1152 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [1184 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [576 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm13, ymm8"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [128 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [160 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[128 + rdi], ymm7"),
        Q!("    vmovdqa         " "[160 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [1216 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [1248 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [1216 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [1248 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [608 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm13"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [192 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [224 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[192 + rdi], ymm7"),
        Q!("    vmovdqa         " "[224 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [1280 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [1312 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [1280 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [1312 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [640 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm13, ymm8"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [256 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [288 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[256 + rdi], ymm7"),
        Q!("    vmovdqa         " "[288 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [1344 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [1376 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [1344 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [1376 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [672 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm13"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [320 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [352 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[320 + rdi], ymm7"),
        Q!("    vmovdqa         " "[352 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [1408 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [1440 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [1408 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [1440 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [704 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm13, ymm8"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [384 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [416 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[384 + rdi], ymm7"),
        Q!("    vmovdqa         " "[416 + rdi], ymm9"),
        Q!("    vmovdqa         " "ymm2, [1472 + rsi]"),
        Q!("    vmovdqa         " "ymm3, [1504 + rsi]"),
        Q!("    vmovdqa         " "ymm4, [1472 + rdx]"),
        Q!("    vmovdqa         " "ymm5, [1504 + rdx]"),
        Q!("    vmovdqa         " "ymm6, [736 + rcx]"),
        Q!("    vpmullw         " "ymm13, ymm1, ymm2"),
        Q!("    vpmullw         " "ymm14, ymm1, ymm3"),
        Q!("    vpmullw         " "ymm7, ymm4, ymm13"),
        Q!("    vpmullw         " "ymm9, ymm5, ymm13"),
        Q!("    vpmullw         " "ymm8, ymm6, ymm14"),
        Q!("    vpmullw         " "ymm10, ymm4, ymm14"),
        Q!("    vpmulhw         " "ymm7, ymm0, ymm7"),
        Q!("    vpmulhw         " "ymm9, ymm0, ymm9"),
        Q!("    vpmulhw         " "ymm8, ymm0, ymm8"),
        Q!("    vpmulhw         " "ymm10, ymm0, ymm10"),
        Q!("    vpmulhw         " "ymm11, ymm4, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm13, ymm6, ymm3"),
        Q!("    vpmulhw         " "ymm14, ymm4, ymm3"),
        Q!("    vpsubw          " "ymm7, ymm11, ymm7"),
        Q!("    vpsubw          " "ymm9, ymm12, ymm9"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm13"),
        Q!("    vpsubw          " "ymm10, ymm14, ymm10"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "ymm8, [448 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [480 + rdi]"),
        Q!("    vpaddw          " "ymm7, ymm8, ymm7"),
        Q!("    vpaddw          " "ymm9, ymm10, ymm9"),
        Q!("    vmovdqa         " "[448 + rdi], ymm7"),
        Q!("    vmovdqa         " "[480 + rdi], ymm9"),

        inout("rdi") r.as_mut_ptr() => _,
        inout("rsi") a.as_ptr() => _,
        inout("rdx") b.as_ptr() => _,
        inout("rcx") bt.as_ptr() => _,
        // clobbers
        out("rax") _,
        out("zmm0") _,
        out("zmm1") _,
        out("zmm10") _,
        out("zmm11") _,
        out("zmm12") _,
        out("zmm13") _,
        out("zmm14") _,
        out("zmm2") _,
        out("zmm3") _,
        out("zmm4") _,
        out("zmm5") _,
        out("zmm6") _,
        out("zmm7") _,
        out("zmm8") _,
        out("zmm9") _,
            )
    };
}
