// generated source. do not edit.
#![allow(non_upper_case_globals, unused_macros, unused_imports)]
use crate::low::macros::*;

// Copyright (c) 2024 The mlkem-native project authors
// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

// ----------------------------------------------------------------------------
// Forward number-theoretic transform from ML-KEM
// Input a[256], qdata[624] (all signed 16-bit words); output a[256] (signed 16-bit words).
//
// The transform is in-place with input and output a[256], with the output
// in bitreversed order. The second parameter is expected to point to a
// table of constants whose definitions can be found in the mlkem-native
// repo or our "tests/test.c".
//
// extern void mlkem_ntt_x86(int16_t a[static 256], const int16_t qdata[static 624]);
//
// Standard x86-64 ABI: RDI = a, RSI = qdata
// Microsoft x64 ABI:   RCX = a, RDX = qdata
// ----------------------------------------------------------------------------

/// Forward number-theoretic transform from ML-KEM
///
/// Input a[256], qdata[624] (all signed 16-bit words); output a[256] (signed 16-bit words).
///
/// The transform is in-place with input and output a[256], with the output
/// in bitreversed order. The second parameter is expected to point to a
/// table of constants whose definitions can be found in the mlkem-native
/// repo or our "tests/test.c".
pub(crate) fn mlkem_ntt(a: &mut [i16; 256], qdata: &[i16; 624]) {
    debug_assert!((a.as_mut_ptr() as usize).is_multiple_of(32));
    debug_assert!((qdata.as_ptr() as usize).is_multiple_of(32));
    // SAFETY: inline assembly. see [crate::low::inline_assembly_safety] for safety info.
    unsafe {
        core::arch::asm!(

        Q!("    endbr64         " ),

        Q!("    mov             " "eax, 0xd010d01"),
        Q!("    vmovd           " "xmm0, eax"),
        Q!("    vpbroadcastd    " "ymm0, xmm0"),
        Q!("    vpbroadcastq    " "ymm15, [64 + rsi]"),
        Q!("    vmovdqa         " "ymm8, [256 + rdi]"),
        Q!("    vmovdqa         " "ymm9, [288 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [320 + rdi]"),
        Q!("    vmovdqa         " "ymm11, [352 + rdi]"),
        Q!("    vpbroadcastq    " "ymm2, [72 + rsi]"),
        Q!("    vpmullw         " "ymm12, ymm8, ymm15"),
        Q!("    vpmullw         " "ymm13, ymm9, ymm15"),
        Q!("    vpmullw         " "ymm14, ymm10, ymm15"),
        Q!("    vpmullw         " "ymm15, ymm11, ymm15"),
        Q!("    vpmulhw         " "ymm8, ymm8, ymm2"),
        Q!("    vpmulhw         " "ymm9, ymm9, ymm2"),
        Q!("    vpmulhw         " "ymm10, ymm10, ymm2"),
        Q!("    vpmulhw         " "ymm11, ymm11, ymm2"),
        Q!("    vmovdqa         " "ymm4, [rdi]"),
        Q!("    vmovdqa         " "ymm5, [32 + rdi]"),
        Q!("    vmovdqa         " "ymm6, [64 + rdi]"),
        Q!("    vmovdqa         " "ymm7, [96 + rdi]"),
        Q!("    vpmulhw         " "ymm12, ymm12, ymm0"),
        Q!("    vpmulhw         " "ymm13, ymm13, ymm0"),
        Q!("    vpmulhw         " "ymm14, ymm14, ymm0"),
        Q!("    vpmulhw         " "ymm15, ymm15, ymm0"),
        Q!("    vpaddw          " "ymm3, ymm4, ymm8"),
        Q!("    vpsubw          " "ymm8, ymm4, ymm8"),
        Q!("    vpaddw          " "ymm4, ymm5, ymm9"),
        Q!("    vpsubw          " "ymm9, ymm5, ymm9"),
        Q!("    vpaddw          " "ymm5, ymm6, ymm10"),
        Q!("    vpsubw          " "ymm10, ymm6, ymm10"),
        Q!("    vpaddw          " "ymm6, ymm7, ymm11"),
        Q!("    vpsubw          " "ymm11, ymm7, ymm11"),
        Q!("    vpsubw          " "ymm3, ymm3, ymm12"),
        Q!("    vpaddw          " "ymm8, ymm8, ymm12"),
        Q!("    vpsubw          " "ymm4, ymm4, ymm13"),
        Q!("    vpaddw          " "ymm9, ymm9, ymm13"),
        Q!("    vpsubw          " "ymm5, ymm5, ymm14"),
        Q!("    vpaddw          " "ymm10, ymm10, ymm14"),
        Q!("    vpsubw          " "ymm6, ymm6, ymm15"),
        Q!("    vpaddw          " "ymm11, ymm11, ymm15"),
        Q!("    vmovdqa         " "[rdi], ymm3"),
        Q!("    vmovdqa         " "[32 + rdi], ymm4"),
        Q!("    vmovdqa         " "[64 + rdi], ymm5"),
        Q!("    vmovdqa         " "[96 + rdi], ymm6"),
        Q!("    vmovdqa         " "[256 + rdi], ymm8"),
        Q!("    vmovdqa         " "[288 + rdi], ymm9"),
        Q!("    vmovdqa         " "[320 + rdi], ymm10"),
        Q!("    vmovdqa         " "[352 + rdi], ymm11"),
        Q!("    vpbroadcastq    " "ymm15, [64 + rsi]"),
        Q!("    vmovdqa         " "ymm8, [384 + rdi]"),
        Q!("    vmovdqa         " "ymm9, [416 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [448 + rdi]"),
        Q!("    vmovdqa         " "ymm11, [480 + rdi]"),
        Q!("    vpbroadcastq    " "ymm2, [72 + rsi]"),
        Q!("    vpmullw         " "ymm12, ymm8, ymm15"),
        Q!("    vpmullw         " "ymm13, ymm9, ymm15"),
        Q!("    vpmullw         " "ymm14, ymm10, ymm15"),
        Q!("    vpmullw         " "ymm15, ymm11, ymm15"),
        Q!("    vpmulhw         " "ymm8, ymm8, ymm2"),
        Q!("    vpmulhw         " "ymm9, ymm9, ymm2"),
        Q!("    vpmulhw         " "ymm10, ymm10, ymm2"),
        Q!("    vpmulhw         " "ymm11, ymm11, ymm2"),
        Q!("    vmovdqa         " "ymm4, [128 + rdi]"),
        Q!("    vmovdqa         " "ymm5, [160 + rdi]"),
        Q!("    vmovdqa         " "ymm6, [192 + rdi]"),
        Q!("    vmovdqa         " "ymm7, [224 + rdi]"),
        Q!("    vpmulhw         " "ymm12, ymm12, ymm0"),
        Q!("    vpmulhw         " "ymm13, ymm13, ymm0"),
        Q!("    vpmulhw         " "ymm14, ymm14, ymm0"),
        Q!("    vpmulhw         " "ymm15, ymm15, ymm0"),
        Q!("    vpaddw          " "ymm3, ymm4, ymm8"),
        Q!("    vpsubw          " "ymm8, ymm4, ymm8"),
        Q!("    vpaddw          " "ymm4, ymm5, ymm9"),
        Q!("    vpsubw          " "ymm9, ymm5, ymm9"),
        Q!("    vpaddw          " "ymm5, ymm6, ymm10"),
        Q!("    vpsubw          " "ymm10, ymm6, ymm10"),
        Q!("    vpaddw          " "ymm6, ymm7, ymm11"),
        Q!("    vpsubw          " "ymm11, ymm7, ymm11"),
        Q!("    vpsubw          " "ymm3, ymm3, ymm12"),
        Q!("    vpaddw          " "ymm8, ymm8, ymm12"),
        Q!("    vpsubw          " "ymm4, ymm4, ymm13"),
        Q!("    vpaddw          " "ymm9, ymm9, ymm13"),
        Q!("    vpsubw          " "ymm5, ymm5, ymm14"),
        Q!("    vpaddw          " "ymm10, ymm10, ymm14"),
        Q!("    vpsubw          " "ymm6, ymm6, ymm15"),
        Q!("    vpaddw          " "ymm11, ymm11, ymm15"),
        Q!("    vmovdqa         " "[128 + rdi], ymm3"),
        Q!("    vmovdqa         " "[160 + rdi], ymm4"),
        Q!("    vmovdqa         " "[192 + rdi], ymm5"),
        Q!("    vmovdqa         " "[224 + rdi], ymm6"),
        Q!("    vmovdqa         " "[384 + rdi], ymm8"),
        Q!("    vmovdqa         " "[416 + rdi], ymm9"),
        Q!("    vmovdqa         " "[448 + rdi], ymm10"),
        Q!("    vmovdqa         " "[480 + rdi], ymm11"),
        Q!("    vmovdqa         " "ymm15, [96 + rsi]"),
        Q!("    vmovdqa         " "ymm8, [128 + rdi]"),
        Q!("    vmovdqa         " "ymm9, [160 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [192 + rdi]"),
        Q!("    vmovdqa         " "ymm11, [224 + rdi]"),
        Q!("    vmovdqa         " "ymm2, [128 + rsi]"),
        Q!("    vpmullw         " "ymm12, ymm8, ymm15"),
        Q!("    vpmullw         " "ymm13, ymm9, ymm15"),
        Q!("    vpmullw         " "ymm14, ymm10, ymm15"),
        Q!("    vpmullw         " "ymm15, ymm11, ymm15"),
        Q!("    vpmulhw         " "ymm8, ymm8, ymm2"),
        Q!("    vpmulhw         " "ymm9, ymm9, ymm2"),
        Q!("    vpmulhw         " "ymm10, ymm10, ymm2"),
        Q!("    vpmulhw         " "ymm11, ymm11, ymm2"),
        Q!("    vmovdqa         " "ymm4, [rdi]"),
        Q!("    vmovdqa         " "ymm5, [32 + rdi]"),
        Q!("    vmovdqa         " "ymm6, [64 + rdi]"),
        Q!("    vmovdqa         " "ymm7, [96 + rdi]"),
        Q!("    vpmulhw         " "ymm12, ymm12, ymm0"),
        Q!("    vpmulhw         " "ymm13, ymm13, ymm0"),
        Q!("    vpmulhw         " "ymm14, ymm14, ymm0"),
        Q!("    vpmulhw         " "ymm15, ymm15, ymm0"),
        Q!("    vpaddw          " "ymm3, ymm4, ymm8"),
        Q!("    vpsubw          " "ymm8, ymm4, ymm8"),
        Q!("    vpaddw          " "ymm4, ymm5, ymm9"),
        Q!("    vpsubw          " "ymm9, ymm5, ymm9"),
        Q!("    vpaddw          " "ymm5, ymm6, ymm10"),
        Q!("    vpsubw          " "ymm10, ymm6, ymm10"),
        Q!("    vpaddw          " "ymm6, ymm7, ymm11"),
        Q!("    vpsubw          " "ymm11, ymm7, ymm11"),
        Q!("    vpsubw          " "ymm3, ymm3, ymm12"),
        Q!("    vpaddw          " "ymm8, ymm8, ymm12"),
        Q!("    vpsubw          " "ymm4, ymm4, ymm13"),
        Q!("    vpaddw          " "ymm9, ymm9, ymm13"),
        Q!("    vpsubw          " "ymm5, ymm5, ymm14"),
        Q!("    vpaddw          " "ymm10, ymm10, ymm14"),
        Q!("    vpsubw          " "ymm6, ymm6, ymm15"),
        Q!("    vpaddw          " "ymm11, ymm11, ymm15"),
        Q!("    vperm2i128      " "ymm7, ymm5, ymm10, 0x20"),
        Q!("    vperm2i128      " "ymm10, ymm5, ymm10, 0x31"),
        Q!("    vperm2i128      " "ymm5, ymm6, ymm11, 0x20"),
        Q!("    vperm2i128      " "ymm11, ymm6, ymm11, 0x31"),
        Q!("    vmovdqa         " "ymm15, [160 + rsi]"),
        Q!("    vmovdqa         " "ymm2, [192 + rsi]"),
        Q!("    vpmullw         " "ymm12, ymm7, ymm15"),
        Q!("    vpmullw         " "ymm13, ymm10, ymm15"),
        Q!("    vpmullw         " "ymm14, ymm5, ymm15"),
        Q!("    vpmullw         " "ymm15, ymm11, ymm15"),
        Q!("    vpmulhw         " "ymm7, ymm7, ymm2"),
        Q!("    vpmulhw         " "ymm10, ymm10, ymm2"),
        Q!("    vpmulhw         " "ymm5, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm11, ymm11, ymm2"),
        Q!("    vperm2i128      " "ymm6, ymm3, ymm8, 0x20"),
        Q!("    vperm2i128      " "ymm8, ymm3, ymm8, 0x31"),
        Q!("    vperm2i128      " "ymm3, ymm4, ymm9, 0x20"),
        Q!("    vperm2i128      " "ymm9, ymm4, ymm9, 0x31"),
        Q!("    vpmulhw         " "ymm12, ymm12, ymm0"),
        Q!("    vpmulhw         " "ymm13, ymm13, ymm0"),
        Q!("    vpmulhw         " "ymm14, ymm14, ymm0"),
        Q!("    vpmulhw         " "ymm15, ymm15, ymm0"),
        Q!("    vpaddw          " "ymm4, ymm6, ymm7"),
        Q!("    vpsubw          " "ymm7, ymm6, ymm7"),
        Q!("    vpaddw          " "ymm6, ymm8, ymm10"),
        Q!("    vpsubw          " "ymm10, ymm8, ymm10"),
        Q!("    vpaddw          " "ymm8, ymm3, ymm5"),
        Q!("    vpsubw          " "ymm5, ymm3, ymm5"),
        Q!("    vpaddw          " "ymm3, ymm9, ymm11"),
        Q!("    vpsubw          " "ymm11, ymm9, ymm11"),
        Q!("    vpsubw          " "ymm4, ymm4, ymm12"),
        Q!("    vpaddw          " "ymm7, ymm7, ymm12"),
        Q!("    vpsubw          " "ymm6, ymm6, ymm13"),
        Q!("    vpaddw          " "ymm10, ymm10, ymm13"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm14"),
        Q!("    vpaddw          " "ymm5, ymm5, ymm14"),
        Q!("    vpsubw          " "ymm3, ymm3, ymm15"),
        Q!("    vpaddw          " "ymm11, ymm11, ymm15"),
        Q!("    vpunpcklqdq     " "ymm9, ymm8, ymm5"),
        Q!("    vpunpckhqdq     " "ymm5, ymm8, ymm5"),
        Q!("    vpunpcklqdq     " "ymm8, ymm3, ymm11"),
        Q!("    vpunpckhqdq     " "ymm11, ymm3, ymm11"),
        Q!("    vmovdqa         " "ymm15, [224 + rsi]"),
        Q!("    vmovdqa         " "ymm2, [256 + rsi]"),
        Q!("    vpmullw         " "ymm12, ymm9, ymm15"),
        Q!("    vpmullw         " "ymm13, ymm5, ymm15"),
        Q!("    vpmullw         " "ymm14, ymm8, ymm15"),
        Q!("    vpmullw         " "ymm15, ymm11, ymm15"),
        Q!("    vpmulhw         " "ymm9, ymm9, ymm2"),
        Q!("    vpmulhw         " "ymm5, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm8, ymm8, ymm2"),
        Q!("    vpmulhw         " "ymm11, ymm11, ymm2"),
        Q!("    vpunpcklqdq     " "ymm3, ymm4, ymm7"),
        Q!("    vpunpckhqdq     " "ymm7, ymm4, ymm7"),
        Q!("    vpunpcklqdq     " "ymm4, ymm6, ymm10"),
        Q!("    vpunpckhqdq     " "ymm10, ymm6, ymm10"),
        Q!("    vpmulhw         " "ymm12, ymm12, ymm0"),
        Q!("    vpmulhw         " "ymm13, ymm13, ymm0"),
        Q!("    vpmulhw         " "ymm14, ymm14, ymm0"),
        Q!("    vpmulhw         " "ymm15, ymm15, ymm0"),
        Q!("    vpaddw          " "ymm6, ymm3, ymm9"),
        Q!("    vpsubw          " "ymm9, ymm3, ymm9"),
        Q!("    vpaddw          " "ymm3, ymm7, ymm5"),
        Q!("    vpsubw          " "ymm5, ymm7, ymm5"),
        Q!("    vpaddw          " "ymm7, ymm4, ymm8"),
        Q!("    vpsubw          " "ymm8, ymm4, ymm8"),
        Q!("    vpaddw          " "ymm4, ymm10, ymm11"),
        Q!("    vpsubw          " "ymm11, ymm10, ymm11"),
        Q!("    vpsubw          " "ymm6, ymm6, ymm12"),
        Q!("    vpaddw          " "ymm9, ymm9, ymm12"),
        Q!("    vpsubw          " "ymm3, ymm3, ymm13"),
        Q!("    vpaddw          " "ymm5, ymm5, ymm13"),
        Q!("    vpsubw          " "ymm7, ymm7, ymm14"),
        Q!("    vpaddw          " "ymm8, ymm8, ymm14"),
        Q!("    vpsubw          " "ymm4, ymm4, ymm15"),
        Q!("    vpaddw          " "ymm11, ymm11, ymm15"),
        Q!("    vmovsldup       " "ymm10, ymm8"),
        Q!("    vpblendd        " "ymm10, ymm7, ymm10, 0xaa"),
        Q!("    vpsrlq          " "ymm7, ymm7, 0x20"),
        Q!("    vpblendd        " "ymm8, ymm7, ymm8, 0xaa"),
        Q!("    vmovsldup       " "ymm7, ymm11"),
        Q!("    vpblendd        " "ymm7, ymm4, ymm7, 0xaa"),
        Q!("    vpsrlq          " "ymm4, ymm4, 0x20"),
        Q!("    vpblendd        " "ymm11, ymm4, ymm11, 0xaa"),
        Q!("    vmovdqa         " "ymm15, [288 + rsi]"),
        Q!("    vmovdqa         " "ymm2, [320 + rsi]"),
        Q!("    vpmullw         " "ymm12, ymm10, ymm15"),
        Q!("    vpmullw         " "ymm13, ymm8, ymm15"),
        Q!("    vpmullw         " "ymm14, ymm7, ymm15"),
        Q!("    vpmullw         " "ymm15, ymm11, ymm15"),
        Q!("    vpmulhw         " "ymm10, ymm10, ymm2"),
        Q!("    vpmulhw         " "ymm8, ymm8, ymm2"),
        Q!("    vpmulhw         " "ymm7, ymm7, ymm2"),
        Q!("    vpmulhw         " "ymm11, ymm11, ymm2"),
        Q!("    vmovsldup       " "ymm4, ymm9"),
        Q!("    vpblendd        " "ymm4, ymm6, ymm4, 0xaa"),
        Q!("    vpsrlq          " "ymm6, ymm6, 0x20"),
        Q!("    vpblendd        " "ymm9, ymm6, ymm9, 0xaa"),
        Q!("    vmovsldup       " "ymm6, ymm5"),
        Q!("    vpblendd        " "ymm6, ymm3, ymm6, 0xaa"),
        Q!("    vpsrlq          " "ymm3, ymm3, 0x20"),
        Q!("    vpblendd        " "ymm5, ymm3, ymm5, 0xaa"),
        Q!("    vpmulhw         " "ymm12, ymm12, ymm0"),
        Q!("    vpmulhw         " "ymm13, ymm13, ymm0"),
        Q!("    vpmulhw         " "ymm14, ymm14, ymm0"),
        Q!("    vpmulhw         " "ymm15, ymm15, ymm0"),
        Q!("    vpaddw          " "ymm3, ymm4, ymm10"),
        Q!("    vpsubw          " "ymm10, ymm4, ymm10"),
        Q!("    vpaddw          " "ymm4, ymm9, ymm8"),
        Q!("    vpsubw          " "ymm8, ymm9, ymm8"),
        Q!("    vpaddw          " "ymm9, ymm6, ymm7"),
        Q!("    vpsubw          " "ymm7, ymm6, ymm7"),
        Q!("    vpaddw          " "ymm6, ymm5, ymm11"),
        Q!("    vpsubw          " "ymm11, ymm5, ymm11"),
        Q!("    vpsubw          " "ymm3, ymm3, ymm12"),
        Q!("    vpaddw          " "ymm10, ymm10, ymm12"),
        Q!("    vpsubw          " "ymm4, ymm4, ymm13"),
        Q!("    vpaddw          " "ymm8, ymm8, ymm13"),
        Q!("    vpsubw          " "ymm9, ymm9, ymm14"),
        Q!("    vpaddw          " "ymm7, ymm7, ymm14"),
        Q!("    vpsubw          " "ymm6, ymm6, ymm15"),
        Q!("    vpaddw          " "ymm11, ymm11, ymm15"),
        Q!("    vpslld          " "ymm5, ymm7, 0x10"),
        Q!("    vpblendw        " "ymm5, ymm9, ymm5, 0xaa"),
        Q!("    vpsrld          " "ymm9, ymm9, 0x10"),
        Q!("    vpblendw        " "ymm7, ymm9, ymm7, 0xaa"),
        Q!("    vpslld          " "ymm9, ymm11, 0x10"),
        Q!("    vpblendw        " "ymm9, ymm6, ymm9, 0xaa"),
        Q!("    vpsrld          " "ymm6, ymm6, 0x10"),
        Q!("    vpblendw        " "ymm11, ymm6, ymm11, 0xaa"),
        Q!("    vmovdqa         " "ymm15, [352 + rsi]"),
        Q!("    vmovdqa         " "ymm2, [384 + rsi]"),
        Q!("    vpmullw         " "ymm12, ymm5, ymm15"),
        Q!("    vpmullw         " "ymm13, ymm7, ymm15"),
        Q!("    vpmullw         " "ymm14, ymm9, ymm15"),
        Q!("    vpmullw         " "ymm15, ymm11, ymm15"),
        Q!("    vpmulhw         " "ymm5, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm7, ymm7, ymm2"),
        Q!("    vpmulhw         " "ymm9, ymm9, ymm2"),
        Q!("    vpmulhw         " "ymm11, ymm11, ymm2"),
        Q!("    vpslld          " "ymm6, ymm10, 0x10"),
        Q!("    vpblendw        " "ymm6, ymm3, ymm6, 0xaa"),
        Q!("    vpsrld          " "ymm3, ymm3, 0x10"),
        Q!("    vpblendw        " "ymm10, ymm3, ymm10, 0xaa"),
        Q!("    vpslld          " "ymm3, ymm8, 0x10"),
        Q!("    vpblendw        " "ymm3, ymm4, ymm3, 0xaa"),
        Q!("    vpsrld          " "ymm4, ymm4, 0x10"),
        Q!("    vpblendw        " "ymm8, ymm4, ymm8, 0xaa"),
        Q!("    vpmulhw         " "ymm12, ymm12, ymm0"),
        Q!("    vpmulhw         " "ymm13, ymm13, ymm0"),
        Q!("    vpmulhw         " "ymm14, ymm14, ymm0"),
        Q!("    vpmulhw         " "ymm15, ymm15, ymm0"),
        Q!("    vpaddw          " "ymm4, ymm6, ymm5"),
        Q!("    vpsubw          " "ymm5, ymm6, ymm5"),
        Q!("    vpaddw          " "ymm6, ymm10, ymm7"),
        Q!("    vpsubw          " "ymm7, ymm10, ymm7"),
        Q!("    vpaddw          " "ymm10, ymm3, ymm9"),
        Q!("    vpsubw          " "ymm9, ymm3, ymm9"),
        Q!("    vpaddw          " "ymm3, ymm8, ymm11"),
        Q!("    vpsubw          " "ymm11, ymm8, ymm11"),
        Q!("    vpsubw          " "ymm4, ymm4, ymm12"),
        Q!("    vpaddw          " "ymm5, ymm5, ymm12"),
        Q!("    vpsubw          " "ymm6, ymm6, ymm13"),
        Q!("    vpaddw          " "ymm7, ymm7, ymm13"),
        Q!("    vpsubw          " "ymm10, ymm10, ymm14"),
        Q!("    vpaddw          " "ymm9, ymm9, ymm14"),
        Q!("    vpsubw          " "ymm3, ymm3, ymm15"),
        Q!("    vpaddw          " "ymm11, ymm11, ymm15"),
        Q!("    vmovdqa         " "ymm14, [416 + rsi]"),
        Q!("    vmovdqa         " "ymm15, [480 + rsi]"),
        Q!("    vmovdqa         " "ymm8, [448 + rsi]"),
        Q!("    vmovdqa         " "ymm2, [512 + rsi]"),
        Q!("    vpmullw         " "ymm12, ymm10, ymm14"),
        Q!("    vpmullw         " "ymm13, ymm3, ymm14"),
        Q!("    vpmullw         " "ymm14, ymm9, ymm15"),
        Q!("    vpmullw         " "ymm15, ymm11, ymm15"),
        Q!("    vpmulhw         " "ymm10, ymm10, ymm8"),
        Q!("    vpmulhw         " "ymm3, ymm3, ymm8"),
        Q!("    vpmulhw         " "ymm9, ymm9, ymm2"),
        Q!("    vpmulhw         " "ymm11, ymm11, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm12, ymm0"),
        Q!("    vpmulhw         " "ymm13, ymm13, ymm0"),
        Q!("    vpmulhw         " "ymm14, ymm14, ymm0"),
        Q!("    vpmulhw         " "ymm15, ymm15, ymm0"),
        Q!("    vpaddw          " "ymm8, ymm4, ymm10"),
        Q!("    vpsubw          " "ymm10, ymm4, ymm10"),
        Q!("    vpaddw          " "ymm4, ymm6, ymm3"),
        Q!("    vpsubw          " "ymm3, ymm6, ymm3"),
        Q!("    vpaddw          " "ymm6, ymm5, ymm9"),
        Q!("    vpsubw          " "ymm9, ymm5, ymm9"),
        Q!("    vpaddw          " "ymm5, ymm7, ymm11"),
        Q!("    vpsubw          " "ymm11, ymm7, ymm11"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm12"),
        Q!("    vpaddw          " "ymm10, ymm10, ymm12"),
        Q!("    vpsubw          " "ymm4, ymm4, ymm13"),
        Q!("    vpaddw          " "ymm3, ymm3, ymm13"),
        Q!("    vpsubw          " "ymm6, ymm6, ymm14"),
        Q!("    vpaddw          " "ymm9, ymm9, ymm14"),
        Q!("    vpsubw          " "ymm5, ymm5, ymm15"),
        Q!("    vpaddw          " "ymm11, ymm11, ymm15"),
        Q!("    vmovdqa         " "[rdi], ymm8"),
        Q!("    vmovdqa         " "[32 + rdi], ymm4"),
        Q!("    vmovdqa         " "[64 + rdi], ymm10"),
        Q!("    vmovdqa         " "[96 + rdi], ymm3"),
        Q!("    vmovdqa         " "[128 + rdi], ymm6"),
        Q!("    vmovdqa         " "[160 + rdi], ymm5"),
        Q!("    vmovdqa         " "[192 + rdi], ymm9"),
        Q!("    vmovdqa         " "[224 + rdi], ymm11"),
        Q!("    vmovdqa         " "ymm15, [544 + rsi]"),
        Q!("    vmovdqa         " "ymm8, [384 + rdi]"),
        Q!("    vmovdqa         " "ymm9, [416 + rdi]"),
        Q!("    vmovdqa         " "ymm10, [448 + rdi]"),
        Q!("    vmovdqa         " "ymm11, [480 + rdi]"),
        Q!("    vmovdqa         " "ymm2, [576 + rsi]"),
        Q!("    vpmullw         " "ymm12, ymm8, ymm15"),
        Q!("    vpmullw         " "ymm13, ymm9, ymm15"),
        Q!("    vpmullw         " "ymm14, ymm10, ymm15"),
        Q!("    vpmullw         " "ymm15, ymm11, ymm15"),
        Q!("    vpmulhw         " "ymm8, ymm8, ymm2"),
        Q!("    vpmulhw         " "ymm9, ymm9, ymm2"),
        Q!("    vpmulhw         " "ymm10, ymm10, ymm2"),
        Q!("    vpmulhw         " "ymm11, ymm11, ymm2"),
        Q!("    vmovdqa         " "ymm4, [256 + rdi]"),
        Q!("    vmovdqa         " "ymm5, [288 + rdi]"),
        Q!("    vmovdqa         " "ymm6, [320 + rdi]"),
        Q!("    vmovdqa         " "ymm7, [352 + rdi]"),
        Q!("    vpmulhw         " "ymm12, ymm12, ymm0"),
        Q!("    vpmulhw         " "ymm13, ymm13, ymm0"),
        Q!("    vpmulhw         " "ymm14, ymm14, ymm0"),
        Q!("    vpmulhw         " "ymm15, ymm15, ymm0"),
        Q!("    vpaddw          " "ymm3, ymm4, ymm8"),
        Q!("    vpsubw          " "ymm8, ymm4, ymm8"),
        Q!("    vpaddw          " "ymm4, ymm5, ymm9"),
        Q!("    vpsubw          " "ymm9, ymm5, ymm9"),
        Q!("    vpaddw          " "ymm5, ymm6, ymm10"),
        Q!("    vpsubw          " "ymm10, ymm6, ymm10"),
        Q!("    vpaddw          " "ymm6, ymm7, ymm11"),
        Q!("    vpsubw          " "ymm11, ymm7, ymm11"),
        Q!("    vpsubw          " "ymm3, ymm3, ymm12"),
        Q!("    vpaddw          " "ymm8, ymm8, ymm12"),
        Q!("    vpsubw          " "ymm4, ymm4, ymm13"),
        Q!("    vpaddw          " "ymm9, ymm9, ymm13"),
        Q!("    vpsubw          " "ymm5, ymm5, ymm14"),
        Q!("    vpaddw          " "ymm10, ymm10, ymm14"),
        Q!("    vpsubw          " "ymm6, ymm6, ymm15"),
        Q!("    vpaddw          " "ymm11, ymm11, ymm15"),
        Q!("    vperm2i128      " "ymm7, ymm5, ymm10, 0x20"),
        Q!("    vperm2i128      " "ymm10, ymm5, ymm10, 0x31"),
        Q!("    vperm2i128      " "ymm5, ymm6, ymm11, 0x20"),
        Q!("    vperm2i128      " "ymm11, ymm6, ymm11, 0x31"),
        Q!("    vmovdqa         " "ymm15, [608 + rsi]"),
        Q!("    vmovdqa         " "ymm2, [640 + rsi]"),
        Q!("    vpmullw         " "ymm12, ymm7, ymm15"),
        Q!("    vpmullw         " "ymm13, ymm10, ymm15"),
        Q!("    vpmullw         " "ymm14, ymm5, ymm15"),
        Q!("    vpmullw         " "ymm15, ymm11, ymm15"),
        Q!("    vpmulhw         " "ymm7, ymm7, ymm2"),
        Q!("    vpmulhw         " "ymm10, ymm10, ymm2"),
        Q!("    vpmulhw         " "ymm5, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm11, ymm11, ymm2"),
        Q!("    vperm2i128      " "ymm6, ymm3, ymm8, 0x20"),
        Q!("    vperm2i128      " "ymm8, ymm3, ymm8, 0x31"),
        Q!("    vperm2i128      " "ymm3, ymm4, ymm9, 0x20"),
        Q!("    vperm2i128      " "ymm9, ymm4, ymm9, 0x31"),
        Q!("    vpmulhw         " "ymm12, ymm12, ymm0"),
        Q!("    vpmulhw         " "ymm13, ymm13, ymm0"),
        Q!("    vpmulhw         " "ymm14, ymm14, ymm0"),
        Q!("    vpmulhw         " "ymm15, ymm15, ymm0"),
        Q!("    vpaddw          " "ymm4, ymm6, ymm7"),
        Q!("    vpsubw          " "ymm7, ymm6, ymm7"),
        Q!("    vpaddw          " "ymm6, ymm8, ymm10"),
        Q!("    vpsubw          " "ymm10, ymm8, ymm10"),
        Q!("    vpaddw          " "ymm8, ymm3, ymm5"),
        Q!("    vpsubw          " "ymm5, ymm3, ymm5"),
        Q!("    vpaddw          " "ymm3, ymm9, ymm11"),
        Q!("    vpsubw          " "ymm11, ymm9, ymm11"),
        Q!("    vpsubw          " "ymm4, ymm4, ymm12"),
        Q!("    vpaddw          " "ymm7, ymm7, ymm12"),
        Q!("    vpsubw          " "ymm6, ymm6, ymm13"),
        Q!("    vpaddw          " "ymm10, ymm10, ymm13"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm14"),
        Q!("    vpaddw          " "ymm5, ymm5, ymm14"),
        Q!("    vpsubw          " "ymm3, ymm3, ymm15"),
        Q!("    vpaddw          " "ymm11, ymm11, ymm15"),
        Q!("    vpunpcklqdq     " "ymm9, ymm8, ymm5"),
        Q!("    vpunpckhqdq     " "ymm5, ymm8, ymm5"),
        Q!("    vpunpcklqdq     " "ymm8, ymm3, ymm11"),
        Q!("    vpunpckhqdq     " "ymm11, ymm3, ymm11"),
        Q!("    vmovdqa         " "ymm15, [672 + rsi]"),
        Q!("    vmovdqa         " "ymm2, [704 + rsi]"),
        Q!("    vpmullw         " "ymm12, ymm9, ymm15"),
        Q!("    vpmullw         " "ymm13, ymm5, ymm15"),
        Q!("    vpmullw         " "ymm14, ymm8, ymm15"),
        Q!("    vpmullw         " "ymm15, ymm11, ymm15"),
        Q!("    vpmulhw         " "ymm9, ymm9, ymm2"),
        Q!("    vpmulhw         " "ymm5, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm8, ymm8, ymm2"),
        Q!("    vpmulhw         " "ymm11, ymm11, ymm2"),
        Q!("    vpunpcklqdq     " "ymm3, ymm4, ymm7"),
        Q!("    vpunpckhqdq     " "ymm7, ymm4, ymm7"),
        Q!("    vpunpcklqdq     " "ymm4, ymm6, ymm10"),
        Q!("    vpunpckhqdq     " "ymm10, ymm6, ymm10"),
        Q!("    vpmulhw         " "ymm12, ymm12, ymm0"),
        Q!("    vpmulhw         " "ymm13, ymm13, ymm0"),
        Q!("    vpmulhw         " "ymm14, ymm14, ymm0"),
        Q!("    vpmulhw         " "ymm15, ymm15, ymm0"),
        Q!("    vpaddw          " "ymm6, ymm3, ymm9"),
        Q!("    vpsubw          " "ymm9, ymm3, ymm9"),
        Q!("    vpaddw          " "ymm3, ymm7, ymm5"),
        Q!("    vpsubw          " "ymm5, ymm7, ymm5"),
        Q!("    vpaddw          " "ymm7, ymm4, ymm8"),
        Q!("    vpsubw          " "ymm8, ymm4, ymm8"),
        Q!("    vpaddw          " "ymm4, ymm10, ymm11"),
        Q!("    vpsubw          " "ymm11, ymm10, ymm11"),
        Q!("    vpsubw          " "ymm6, ymm6, ymm12"),
        Q!("    vpaddw          " "ymm9, ymm9, ymm12"),
        Q!("    vpsubw          " "ymm3, ymm3, ymm13"),
        Q!("    vpaddw          " "ymm5, ymm5, ymm13"),
        Q!("    vpsubw          " "ymm7, ymm7, ymm14"),
        Q!("    vpaddw          " "ymm8, ymm8, ymm14"),
        Q!("    vpsubw          " "ymm4, ymm4, ymm15"),
        Q!("    vpaddw          " "ymm11, ymm11, ymm15"),
        Q!("    vmovsldup       " "ymm10, ymm8"),
        Q!("    vpblendd        " "ymm10, ymm7, ymm10, 0xaa"),
        Q!("    vpsrlq          " "ymm7, ymm7, 0x20"),
        Q!("    vpblendd        " "ymm8, ymm7, ymm8, 0xaa"),
        Q!("    vmovsldup       " "ymm7, ymm11"),
        Q!("    vpblendd        " "ymm7, ymm4, ymm7, 0xaa"),
        Q!("    vpsrlq          " "ymm4, ymm4, 0x20"),
        Q!("    vpblendd        " "ymm11, ymm4, ymm11, 0xaa"),
        Q!("    vmovdqa         " "ymm15, [736 + rsi]"),
        Q!("    vmovdqa         " "ymm2, [768 + rsi]"),
        Q!("    vpmullw         " "ymm12, ymm10, ymm15"),
        Q!("    vpmullw         " "ymm13, ymm8, ymm15"),
        Q!("    vpmullw         " "ymm14, ymm7, ymm15"),
        Q!("    vpmullw         " "ymm15, ymm11, ymm15"),
        Q!("    vpmulhw         " "ymm10, ymm10, ymm2"),
        Q!("    vpmulhw         " "ymm8, ymm8, ymm2"),
        Q!("    vpmulhw         " "ymm7, ymm7, ymm2"),
        Q!("    vpmulhw         " "ymm11, ymm11, ymm2"),
        Q!("    vmovsldup       " "ymm4, ymm9"),
        Q!("    vpblendd        " "ymm4, ymm6, ymm4, 0xaa"),
        Q!("    vpsrlq          " "ymm6, ymm6, 0x20"),
        Q!("    vpblendd        " "ymm9, ymm6, ymm9, 0xaa"),
        Q!("    vmovsldup       " "ymm6, ymm5"),
        Q!("    vpblendd        " "ymm6, ymm3, ymm6, 0xaa"),
        Q!("    vpsrlq          " "ymm3, ymm3, 0x20"),
        Q!("    vpblendd        " "ymm5, ymm3, ymm5, 0xaa"),
        Q!("    vpmulhw         " "ymm12, ymm12, ymm0"),
        Q!("    vpmulhw         " "ymm13, ymm13, ymm0"),
        Q!("    vpmulhw         " "ymm14, ymm14, ymm0"),
        Q!("    vpmulhw         " "ymm15, ymm15, ymm0"),
        Q!("    vpaddw          " "ymm3, ymm4, ymm10"),
        Q!("    vpsubw          " "ymm10, ymm4, ymm10"),
        Q!("    vpaddw          " "ymm4, ymm9, ymm8"),
        Q!("    vpsubw          " "ymm8, ymm9, ymm8"),
        Q!("    vpaddw          " "ymm9, ymm6, ymm7"),
        Q!("    vpsubw          " "ymm7, ymm6, ymm7"),
        Q!("    vpaddw          " "ymm6, ymm5, ymm11"),
        Q!("    vpsubw          " "ymm11, ymm5, ymm11"),
        Q!("    vpsubw          " "ymm3, ymm3, ymm12"),
        Q!("    vpaddw          " "ymm10, ymm10, ymm12"),
        Q!("    vpsubw          " "ymm4, ymm4, ymm13"),
        Q!("    vpaddw          " "ymm8, ymm8, ymm13"),
        Q!("    vpsubw          " "ymm9, ymm9, ymm14"),
        Q!("    vpaddw          " "ymm7, ymm7, ymm14"),
        Q!("    vpsubw          " "ymm6, ymm6, ymm15"),
        Q!("    vpaddw          " "ymm11, ymm11, ymm15"),
        Q!("    vpslld          " "ymm5, ymm7, 0x10"),
        Q!("    vpblendw        " "ymm5, ymm9, ymm5, 0xaa"),
        Q!("    vpsrld          " "ymm9, ymm9, 0x10"),
        Q!("    vpblendw        " "ymm7, ymm9, ymm7, 0xaa"),
        Q!("    vpslld          " "ymm9, ymm11, 0x10"),
        Q!("    vpblendw        " "ymm9, ymm6, ymm9, 0xaa"),
        Q!("    vpsrld          " "ymm6, ymm6, 0x10"),
        Q!("    vpblendw        " "ymm11, ymm6, ymm11, 0xaa"),
        Q!("    vmovdqa         " "ymm15, [800 + rsi]"),
        Q!("    vmovdqa         " "ymm2, [832 + rsi]"),
        Q!("    vpmullw         " "ymm12, ymm5, ymm15"),
        Q!("    vpmullw         " "ymm13, ymm7, ymm15"),
        Q!("    vpmullw         " "ymm14, ymm9, ymm15"),
        Q!("    vpmullw         " "ymm15, ymm11, ymm15"),
        Q!("    vpmulhw         " "ymm5, ymm5, ymm2"),
        Q!("    vpmulhw         " "ymm7, ymm7, ymm2"),
        Q!("    vpmulhw         " "ymm9, ymm9, ymm2"),
        Q!("    vpmulhw         " "ymm11, ymm11, ymm2"),
        Q!("    vpslld          " "ymm6, ymm10, 0x10"),
        Q!("    vpblendw        " "ymm6, ymm3, ymm6, 0xaa"),
        Q!("    vpsrld          " "ymm3, ymm3, 0x10"),
        Q!("    vpblendw        " "ymm10, ymm3, ymm10, 0xaa"),
        Q!("    vpslld          " "ymm3, ymm8, 0x10"),
        Q!("    vpblendw        " "ymm3, ymm4, ymm3, 0xaa"),
        Q!("    vpsrld          " "ymm4, ymm4, 0x10"),
        Q!("    vpblendw        " "ymm8, ymm4, ymm8, 0xaa"),
        Q!("    vpmulhw         " "ymm12, ymm12, ymm0"),
        Q!("    vpmulhw         " "ymm13, ymm13, ymm0"),
        Q!("    vpmulhw         " "ymm14, ymm14, ymm0"),
        Q!("    vpmulhw         " "ymm15, ymm15, ymm0"),
        Q!("    vpaddw          " "ymm4, ymm6, ymm5"),
        Q!("    vpsubw          " "ymm5, ymm6, ymm5"),
        Q!("    vpaddw          " "ymm6, ymm10, ymm7"),
        Q!("    vpsubw          " "ymm7, ymm10, ymm7"),
        Q!("    vpaddw          " "ymm10, ymm3, ymm9"),
        Q!("    vpsubw          " "ymm9, ymm3, ymm9"),
        Q!("    vpaddw          " "ymm3, ymm8, ymm11"),
        Q!("    vpsubw          " "ymm11, ymm8, ymm11"),
        Q!("    vpsubw          " "ymm4, ymm4, ymm12"),
        Q!("    vpaddw          " "ymm5, ymm5, ymm12"),
        Q!("    vpsubw          " "ymm6, ymm6, ymm13"),
        Q!("    vpaddw          " "ymm7, ymm7, ymm13"),
        Q!("    vpsubw          " "ymm10, ymm10, ymm14"),
        Q!("    vpaddw          " "ymm9, ymm9, ymm14"),
        Q!("    vpsubw          " "ymm3, ymm3, ymm15"),
        Q!("    vpaddw          " "ymm11, ymm11, ymm15"),
        Q!("    vmovdqa         " "ymm14, [864 + rsi]"),
        Q!("    vmovdqa         " "ymm15, [928 + rsi]"),
        Q!("    vmovdqa         " "ymm8, [896 + rsi]"),
        Q!("    vmovdqa         " "ymm2, [960 + rsi]"),
        Q!("    vpmullw         " "ymm12, ymm10, ymm14"),
        Q!("    vpmullw         " "ymm13, ymm3, ymm14"),
        Q!("    vpmullw         " "ymm14, ymm9, ymm15"),
        Q!("    vpmullw         " "ymm15, ymm11, ymm15"),
        Q!("    vpmulhw         " "ymm10, ymm10, ymm8"),
        Q!("    vpmulhw         " "ymm3, ymm3, ymm8"),
        Q!("    vpmulhw         " "ymm9, ymm9, ymm2"),
        Q!("    vpmulhw         " "ymm11, ymm11, ymm2"),
        Q!("    vpmulhw         " "ymm12, ymm12, ymm0"),
        Q!("    vpmulhw         " "ymm13, ymm13, ymm0"),
        Q!("    vpmulhw         " "ymm14, ymm14, ymm0"),
        Q!("    vpmulhw         " "ymm15, ymm15, ymm0"),
        Q!("    vpaddw          " "ymm8, ymm4, ymm10"),
        Q!("    vpsubw          " "ymm10, ymm4, ymm10"),
        Q!("    vpaddw          " "ymm4, ymm6, ymm3"),
        Q!("    vpsubw          " "ymm3, ymm6, ymm3"),
        Q!("    vpaddw          " "ymm6, ymm5, ymm9"),
        Q!("    vpsubw          " "ymm9, ymm5, ymm9"),
        Q!("    vpaddw          " "ymm5, ymm7, ymm11"),
        Q!("    vpsubw          " "ymm11, ymm7, ymm11"),
        Q!("    vpsubw          " "ymm8, ymm8, ymm12"),
        Q!("    vpaddw          " "ymm10, ymm10, ymm12"),
        Q!("    vpsubw          " "ymm4, ymm4, ymm13"),
        Q!("    vpaddw          " "ymm3, ymm3, ymm13"),
        Q!("    vpsubw          " "ymm6, ymm6, ymm14"),
        Q!("    vpaddw          " "ymm9, ymm9, ymm14"),
        Q!("    vpsubw          " "ymm5, ymm5, ymm15"),
        Q!("    vpaddw          " "ymm11, ymm11, ymm15"),
        Q!("    vmovdqa         " "[256 + rdi], ymm8"),
        Q!("    vmovdqa         " "[288 + rdi], ymm4"),
        Q!("    vmovdqa         " "[320 + rdi], ymm10"),
        Q!("    vmovdqa         " "[352 + rdi], ymm3"),
        Q!("    vmovdqa         " "[384 + rdi], ymm6"),
        Q!("    vmovdqa         " "[416 + rdi], ymm5"),
        Q!("    vmovdqa         " "[448 + rdi], ymm9"),
        Q!("    vmovdqa         " "[480 + rdi], ymm11"),

        inout("rdi") a.as_mut_ptr() => _,
        inout("rsi") qdata.as_ptr() => _,
        // clobbers
        out("rax") _,
        out("zmm0") _,
        out("zmm10") _,
        out("zmm11") _,
        out("zmm12") _,
        out("zmm13") _,
        out("zmm14") _,
        out("zmm15") _,
        out("zmm2") _,
        out("zmm3") _,
        out("zmm4") _,
        out("zmm5") _,
        out("zmm6") _,
        out("zmm7") _,
        out("zmm8") _,
        out("zmm9") _,
            )
    };
}
