#![allow(non_upper_case_globals, unused_macros, unused_imports)]
use crate::low::macros::*;

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT-0

// ----------------------------------------------------------------------------
// Point doubling on NIST curve P-256 in Montgomery-Jacobian coordinates
//
//    extern void p256_montjdouble
//      (uint64_t p3[static 12],uint64_t p1[static 12]);
//
// Does p3 := 2 * p1 where all points are regarded as Jacobian triples with
// each coordinate in the Montgomery domain, i.e. x' = (2^256 * x) mod p_256.
// A Jacobian triple (x',y',z') represents affine point (x/z^2,y/z^3).
//
// Standard ARM ABI: X0 = p3, X1 = p1
// ----------------------------------------------------------------------------

// This is functionally equivalent to p256_montjdouble in unopt/p256_montjdouble.S.
// This is the result of doing the following sequence of optimizations:
//   1. Function inlining
//   2. Eliminating redundant load/store instructions
//   3. Folding (add addr, const) + load/store
// Function inlining is done manually. The second and third optimizations are
// done by a script.

macro_rules! NUMSIZE {
    () => {
        Q!("32")
    };
}
macro_rules! NSPACE { () => { Q!("# (" NUMSIZE!() "* 6)") } }

pub fn p256_montjdouble(p3: &mut [u64; 12], p1: &[u64; 12]) {
    unsafe {
        core::arch::asm!(


        Q!("    sub             " "sp, sp, " NSPACE!() "+ 80"),
        Q!("    stp             " "x19, x20, [sp, " NSPACE!() "]"),
        Q!("    stp             " "x21, x22, [sp, " NSPACE!() "+ 16]"),
        Q!("    stp             " "x23, x24, [sp, " NSPACE!() "+ 32]"),
        Q!("    stp             " "x25, x26, [sp, " NSPACE!() "+ 48]"),
        Q!("    stp             " "x27, xzr, [sp, " NSPACE!() "+ 64]"),

        Q!("    mov             " "x19, x0"),
        Q!("    mov             " "x20, x1"),
        Q!("    mov             " "x0, sp"),
        Q!("    ldr             " "q19, [x20, #64]"),
        Q!("    ldp             " "x9, x13, [x20, #64]"),
        Q!("    ldr             " "q23, [x20, #80]"),
        Q!("    ldr             " "q0, [x20, #64]"),
        Q!("    ldp             " "x1, x10, [x20, #80]"),
        Q!("    uzp2            " "v29.4s, v19.4s, v19.4s"),
        Q!("    xtn             " "v4.2s, v19.2d"),
        Q!("    umulh           " "x8, x9, x13"),
        Q!("    rev64           " "v20.4s, v23.4s"),
        Q!("    umull           " "v16.2d, v19.2s, v19.2s"),
        Q!("    umull           " "v1.2d, v29.2s, v4.2s"),
        Q!("    mul             " "v20.4s, v20.4s, v0.4s"),
        Q!("    subs            " "x14, x9, x13"),
        Q!("    umulh           " "x15, x9, x1"),
        Q!("    mov             " "x16, v16.d[1]"),
        Q!("    umull2          " "v4.2d, v19.4s, v19.4s"),
        Q!("    mov             " "x4, v16.d[0]"),
        Q!("    uzp1            " "v17.4s, v23.4s, v0.4s"),
        Q!("    uaddlp          " "v19.2d, v20.4s"),
        Q!("    lsr             " "x7, x8, #63"),
        Q!("    mul             " "x11, x9, x13"),
        Q!("    mov             " "x12, v1.d[0]"),
        Q!("    csetm           " "x5, cc"),
        Q!("    cneg            " "x6, x14, cc"),
        Q!("    mov             " "x3, v4.d[1]"),
        Q!("    mov             " "x14, v4.d[0]"),
        Q!("    subs            " "x2, x10, x1"),
        Q!("    mov             " "x9, v1.d[1]"),
        Q!("    cneg            " "x17, x2, cc"),
        Q!("    cinv            " "x2, x5, cc"),
        Q!("    adds            " "x5, x4, x12, lsl #33"),
        Q!("    extr            " "x4, x8, x11, #63"),
        Q!("    lsr             " "x8, x12, #31"),
        Q!("    uzp1            " "v20.4s, v0.4s, v0.4s"),
        Q!("    shl             " "v19.2d, v19.2d, #32"),
        Q!("    adc             " "x16, x16, x8"),
        Q!("    adds            " "x8, x14, x9, lsl #33"),
        Q!("    lsr             " "x14, x9, #31"),
        Q!("    lsl             " "x9, x5, #32"),
        Q!("    umlal           " "v19.2d, v20.2s, v17.2s"),
        Q!("    adc             " "x14, x3, x14"),
        Q!("    adds            " "x16, x16, x11, lsl #1"),
        Q!("    lsr             " "x3, x5, #32"),
        Q!("    umulh           " "x12, x6, x17"),
        Q!("    adcs            " "x4, x8, x4"),
        Q!("    adc             " "x11, x14, x7"),
        Q!("    subs            " "x8, x5, x9"),
        Q!("    sbc             " "x5, x5, x3"),
        Q!("    adds            " "x16, x16, x9"),
        Q!("    mov             " "x14, v19.d[0]"),
        Q!("    mul             " "x17, x6, x17"),
        Q!("    adcs            " "x3, x4, x3"),
        Q!("    lsl             " "x7, x16, #32"),
        Q!("    umulh           " "x13, x13, x10"),
        Q!("    adcs            " "x11, x11, x8"),
        Q!("    lsr             " "x8, x16, #32"),
        Q!("    adc             " "x5, x5, xzr"),
        Q!("    subs            " "x9, x16, x7"),
        Q!("    sbc             " "x16, x16, x8"),
        Q!("    adds            " "x7, x3, x7"),
        Q!("    mov             " "x3, v19.d[1]"),
        Q!("    adcs            " "x6, x11, x8"),
        Q!("    umulh           " "x11, x1, x10"),
        Q!("    adcs            " "x5, x5, x9"),
        Q!("    eor             " "x8, x12, x2"),
        Q!("    adc             " "x9, x16, xzr"),
        Q!("    adds            " "x16, x14, x15"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x12, x16, x3"),
        Q!("    eor             " "x16, x17, x2"),
        Q!("    mul             " "x4, x1, x10"),
        Q!("    adcs            " "x15, x15, x13"),
        Q!("    adc             " "x17, x13, xzr"),
        Q!("    adds            " "x15, x15, x3"),
        Q!("    adc             " "x3, x17, xzr"),
        Q!("    cmn             " "x2, #0x1"),
        Q!("    mul             " "x17, x10, x10"),
        Q!("    adcs            " "x12, x12, x16"),
        Q!("    adcs            " "x16, x15, x8"),
        Q!("    umulh           " "x10, x10, x10"),
        Q!("    adc             " "x2, x3, x2"),
        Q!("    adds            " "x14, x14, x14"),
        Q!("    adcs            " "x12, x12, x12"),
        Q!("    adcs            " "x16, x16, x16"),
        Q!("    adcs            " "x2, x2, x2"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    adds            " "x14, x14, x7"),
        Q!("    mul             " "x3, x1, x1"),
        Q!("    adcs            " "x12, x12, x6"),
        Q!("    lsr             " "x7, x14, #32"),
        Q!("    adcs            " "x16, x16, x5"),
        Q!("    lsl             " "x5, x14, #32"),
        Q!("    umulh           " "x13, x1, x1"),
        Q!("    adcs            " "x2, x2, x9"),
        Q!("    mov             " "x6, #0xffffffff"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x8, x4, x4"),
        Q!("    adcs            " "x1, x11, x11"),
        Q!("    mov             " "x11, #0xffffffff00000001"),
        Q!("    adc             " "x4, xzr, xzr"),
        Q!("    subs            " "x9, x14, x5"),
        Q!("    sbc             " "x14, x14, x7"),
        Q!("    adds            " "x12, x12, x5"),
        Q!("    adcs            " "x16, x16, x7"),
        Q!("    lsl             " "x5, x12, #32"),
        Q!("    lsr             " "x7, x12, #32"),
        Q!("    adcs            " "x2, x2, x9"),
        Q!("    adcs            " "x14, x15, x14"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    subs            " "x9, x12, x5"),
        Q!("    sbc             " "x12, x12, x7"),
        Q!("    adds            " "x16, x16, x5"),
        Q!("    adcs            " "x2, x2, x7"),
        Q!("    adcs            " "x14, x14, x9"),
        Q!("    adcs            " "x12, x15, x12"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    adds            " "x16, x16, x3"),
        Q!("    adcs            " "x2, x2, x13"),
        Q!("    adcs            " "x14, x14, x17"),
        Q!("    adcs            " "x12, x12, x10"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x2, x2, x8"),
        Q!("    adcs            " "x14, x14, x1"),
        Q!("    adcs            " "x12, x12, x4"),
        Q!("    adcs            " "x15, x15, xzr"),
        Q!("    adds            " "x3, x16, #0x1"),
        Q!("    sbcs            " "x5, x2, x6"),
        Q!("    sbcs            " "x8, x14, xzr"),
        Q!("    sbcs            " "x11, x12, x11"),
        Q!("    sbcs            " "xzr, x15, xzr"),
        Q!("    csel            " "x21, x3, x16, cs"),
        Q!("    csel            " "x22, x8, x14, cs"),
        Q!("    csel            " "x23, x11, x12, cs"),
        Q!("    csel            " "x24, x5, x2, cs"),
        Q!("    stp             " "x22, x23, [x0, #16]"),
        Q!("    stp             " "x21, x24, [x0]"),
        Q!("    ldr             " "q19, [x20, #32]"),
        Q!("    ldp             " "x9, x13, [x20, #32]"),
        Q!("    ldr             " "q23, [x20, #48]"),
        Q!("    ldr             " "q0, [x20, #32]"),
        Q!("    ldp             " "x1, x10, [x20, #48]"),
        Q!("    uzp2            " "v29.4s, v19.4s, v19.4s"),
        Q!("    xtn             " "v4.2s, v19.2d"),
        Q!("    umulh           " "x8, x9, x13"),
        Q!("    rev64           " "v20.4s, v23.4s"),
        Q!("    umull           " "v16.2d, v19.2s, v19.2s"),
        Q!("    umull           " "v1.2d, v29.2s, v4.2s"),
        Q!("    mul             " "v20.4s, v20.4s, v0.4s"),
        Q!("    subs            " "x14, x9, x13"),
        Q!("    umulh           " "x15, x9, x1"),
        Q!("    mov             " "x16, v16.d[1]"),
        Q!("    umull2          " "v4.2d, v19.4s, v19.4s"),
        Q!("    mov             " "x4, v16.d[0]"),
        Q!("    uzp1            " "v17.4s, v23.4s, v0.4s"),
        Q!("    uaddlp          " "v19.2d, v20.4s"),
        Q!("    lsr             " "x7, x8, #63"),
        Q!("    mul             " "x11, x9, x13"),
        Q!("    mov             " "x12, v1.d[0]"),
        Q!("    csetm           " "x5, cc"),
        Q!("    cneg            " "x6, x14, cc"),
        Q!("    mov             " "x3, v4.d[1]"),
        Q!("    mov             " "x14, v4.d[0]"),
        Q!("    subs            " "x2, x10, x1"),
        Q!("    mov             " "x9, v1.d[1]"),
        Q!("    cneg            " "x17, x2, cc"),
        Q!("    cinv            " "x2, x5, cc"),
        Q!("    adds            " "x5, x4, x12, lsl #33"),
        Q!("    extr            " "x4, x8, x11, #63"),
        Q!("    lsr             " "x8, x12, #31"),
        Q!("    uzp1            " "v20.4s, v0.4s, v0.4s"),
        Q!("    shl             " "v19.2d, v19.2d, #32"),
        Q!("    adc             " "x16, x16, x8"),
        Q!("    adds            " "x8, x14, x9, lsl #33"),
        Q!("    lsr             " "x14, x9, #31"),
        Q!("    lsl             " "x9, x5, #32"),
        Q!("    umlal           " "v19.2d, v20.2s, v17.2s"),
        Q!("    adc             " "x14, x3, x14"),
        Q!("    adds            " "x16, x16, x11, lsl #1"),
        Q!("    lsr             " "x3, x5, #32"),
        Q!("    umulh           " "x12, x6, x17"),
        Q!("    adcs            " "x4, x8, x4"),
        Q!("    adc             " "x11, x14, x7"),
        Q!("    subs            " "x8, x5, x9"),
        Q!("    sbc             " "x5, x5, x3"),
        Q!("    adds            " "x16, x16, x9"),
        Q!("    mov             " "x14, v19.d[0]"),
        Q!("    mul             " "x17, x6, x17"),
        Q!("    adcs            " "x3, x4, x3"),
        Q!("    lsl             " "x7, x16, #32"),
        Q!("    umulh           " "x13, x13, x10"),
        Q!("    adcs            " "x11, x11, x8"),
        Q!("    lsr             " "x8, x16, #32"),
        Q!("    adc             " "x5, x5, xzr"),
        Q!("    subs            " "x9, x16, x7"),
        Q!("    sbc             " "x16, x16, x8"),
        Q!("    adds            " "x7, x3, x7"),
        Q!("    mov             " "x3, v19.d[1]"),
        Q!("    adcs            " "x6, x11, x8"),
        Q!("    umulh           " "x11, x1, x10"),
        Q!("    adcs            " "x5, x5, x9"),
        Q!("    eor             " "x8, x12, x2"),
        Q!("    adc             " "x9, x16, xzr"),
        Q!("    adds            " "x16, x14, x15"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x12, x16, x3"),
        Q!("    eor             " "x16, x17, x2"),
        Q!("    mul             " "x4, x1, x10"),
        Q!("    adcs            " "x15, x15, x13"),
        Q!("    adc             " "x17, x13, xzr"),
        Q!("    adds            " "x15, x15, x3"),
        Q!("    adc             " "x3, x17, xzr"),
        Q!("    cmn             " "x2, #0x1"),
        Q!("    mul             " "x17, x10, x10"),
        Q!("    adcs            " "x12, x12, x16"),
        Q!("    adcs            " "x16, x15, x8"),
        Q!("    umulh           " "x10, x10, x10"),
        Q!("    adc             " "x2, x3, x2"),
        Q!("    adds            " "x14, x14, x14"),
        Q!("    adcs            " "x12, x12, x12"),
        Q!("    adcs            " "x16, x16, x16"),
        Q!("    adcs            " "x2, x2, x2"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    adds            " "x14, x14, x7"),
        Q!("    mul             " "x3, x1, x1"),
        Q!("    adcs            " "x12, x12, x6"),
        Q!("    lsr             " "x7, x14, #32"),
        Q!("    adcs            " "x16, x16, x5"),
        Q!("    lsl             " "x5, x14, #32"),
        Q!("    umulh           " "x13, x1, x1"),
        Q!("    adcs            " "x2, x2, x9"),
        Q!("    mov             " "x6, #0xffffffff"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x8, x4, x4"),
        Q!("    adcs            " "x1, x11, x11"),
        Q!("    mov             " "x11, #0xffffffff00000001"),
        Q!("    adc             " "x4, xzr, xzr"),
        Q!("    subs            " "x9, x14, x5"),
        Q!("    sbc             " "x14, x14, x7"),
        Q!("    adds            " "x12, x12, x5"),
        Q!("    adcs            " "x16, x16, x7"),
        Q!("    lsl             " "x5, x12, #32"),
        Q!("    lsr             " "x7, x12, #32"),
        Q!("    adcs            " "x2, x2, x9"),
        Q!("    adcs            " "x14, x15, x14"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    subs            " "x9, x12, x5"),
        Q!("    sbc             " "x12, x12, x7"),
        Q!("    adds            " "x16, x16, x5"),
        Q!("    adcs            " "x2, x2, x7"),
        Q!("    adcs            " "x14, x14, x9"),
        Q!("    adcs            " "x12, x15, x12"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    adds            " "x16, x16, x3"),
        Q!("    adcs            " "x2, x2, x13"),
        Q!("    adcs            " "x14, x14, x17"),
        Q!("    adcs            " "x12, x12, x10"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x2, x2, x8"),
        Q!("    adcs            " "x14, x14, x1"),
        Q!("    adcs            " "x12, x12, x4"),
        Q!("    adcs            " "x15, x15, xzr"),
        Q!("    adds            " "x3, x16, #0x1"),
        Q!("    sbcs            " "x5, x2, x6"),
        Q!("    sbcs            " "x8, x14, xzr"),
        Q!("    sbcs            " "x11, x12, x11"),
        Q!("    sbcs            " "xzr, x15, xzr"),
        Q!("    csel            " "x16, x3, x16, cs"),
        Q!("    csel            " "x14, x8, x14, cs"),
        Q!("    csel            " "x12, x11, x12, cs"),
        Q!("    csel            " "x2, x5, x2, cs"),
        Q!("    stp             " "x14, x12, [sp, #48]"),
        Q!("    stp             " "x16, x2, [sp, #32]"),
        Q!("    ldp             " "x5, x6, [x20, #0]"),
        Q!("    subs            " "x5, x5, x21"),
        Q!("    sbcs            " "x6, x6, x24"),
        Q!("    ldp             " "x7, x8, [x20, #16]"),
        Q!("    sbcs            " "x7, x7, x22"),
        Q!("    sbcs            " "x8, x8, x23"),
        Q!("    csetm           " "x3, cc"),
        Q!("    adds            " "x10, x5, x3"),
        Q!("    and             " "x4, x3, #0xffffffff"),
        Q!("    adcs            " "x25, x6, x4"),
        Q!("    adcs            " "x26, x7, xzr"),
        Q!("    and             " "x4, x3, #0xffffffff00000001"),
        Q!("    adc             " "x27, x8, x4"),
        Q!("    stp             " "x10, x25, [sp, #96]"),
        Q!("    stp             " "x26, x27, [sp, #112]"),
        Q!("    ldp             " "x5, x6, [x20]"),
        Q!("    adds            " "x5, x5, x21"),
        Q!("    adcs            " "x6, x6, x24"),
        Q!("    ldp             " "x7, x8, [x20, #16]"),
        Q!("    adcs            " "x7, x7, x22"),
        Q!("    adcs            " "x8, x8, x23"),
        Q!("    csetm           " "x3, cs"),
        Q!("    subs            " "x9, x5, x3"),
        Q!("    and             " "x1, x3, #0xffffffff"),
        Q!("    sbcs            " "x5, x6, x1"),
        Q!("    sbcs            " "x7, x7, xzr"),
        Q!("    and             " "x2, x3, #0xffffffff00000001"),
        Q!("    sbc             " "x8, x8, x2"),
        Q!("    stp             " "x9, x5, [sp, #64]"),
        Q!("    stp             " "x7, x8, [sp, #80]"),
        Q!("    ldr             " "q20, [sp, #96]"),
        Q!("    ldr             " "q0, [sp, #64]"),
        Q!("    rev64           " "v16.4s, v20.4s"),
        Q!("    subs            " "x4, x9, x5"),
        Q!("    csetm           " "x3, cc"),
        Q!("    cneg            " "x13, x4, cc"),
        Q!("    mul             " "v16.4s, v16.4s, v0.4s"),
        Q!("    umulh           " "x12, x5, x25"),
        Q!("    uzp1            " "v28.4s, v20.4s, v0.4s"),
        Q!("    subs            " "x14, x7, x9"),
        Q!("    ldr             " "q20, [sp, #112]"),
        Q!("    sbcs            " "x5, x8, x5"),
        Q!("    ngc             " "x17, xzr"),
        Q!("    subs            " "x8, x7, x8"),
        Q!("    uaddlp          " "v27.2d, v16.4s"),
        Q!("    umulh           " "x4, x9, x10"),
        Q!("    uzp1            " "v21.4s, v0.4s, v0.4s"),
        Q!("    cneg            " "x11, x8, cc"),
        Q!("    shl             " "v17.2d, v27.2d, #32"),
        Q!("    csetm           " "x15, cc"),
        Q!("    subs            " "x9, x25, x10"),
        Q!("    eor             " "x7, x14, x17"),
        Q!("    umlal           " "v17.2d, v21.2s, v28.2s"),
        Q!("    cneg            " "x8, x9, cc"),
        Q!("    cinv            " "x9, x3, cc"),
        Q!("    cmn             " "x17, #0x1"),
        Q!("    ldr             " "q28, [sp, #80]"),
        Q!("    adcs            " "x14, x7, xzr"),
        Q!("    mul             " "x7, x13, x8"),
        Q!("    eor             " "x1, x5, x17"),
        Q!("    adcs            " "x5, x1, xzr"),
        Q!("    xtn             " "v1.2s, v20.2d"),
        Q!("    mov             " "x1, v17.d[0]"),
        Q!("    mov             " "x3, v17.d[1]"),
        Q!("    uzp2            " "v16.4s, v20.4s, v20.4s"),
        Q!("    umulh           " "x16, x13, x8"),
        Q!("    eor             " "x13, x7, x9"),
        Q!("    adds            " "x8, x1, x3"),
        Q!("    adcs            " "x7, x4, x12"),
        Q!("    xtn             " "v0.2s, v28.2d"),
        Q!("    adcs            " "x12, x12, xzr"),
        Q!("    adds            " "x8, x4, x8"),
        Q!("    adcs            " "x3, x3, x7"),
        Q!("    adcs            " "x12, x12, xzr"),
        Q!("    cmn             " "x9, #0x1"),
        Q!("    adcs            " "x8, x8, x13"),
        Q!("    eor             " "x13, x16, x9"),
        Q!("    adcs            " "x16, x3, x13"),
        Q!("    lsl             " "x3, x1, #32"),
        Q!("    adc             " "x13, x12, x9"),
        Q!("    subs            " "x12, x10, x26"),
        Q!("    sbcs            " "x9, x25, x27"),
        Q!("    lsr             " "x10, x1, #32"),
        Q!("    ngc             " "x4, xzr"),
        Q!("    subs            " "x6, x27, x26"),
        Q!("    cinv            " "x2, x15, cc"),
        Q!("    cneg            " "x6, x6, cc"),
        Q!("    subs            " "x7, x1, x3"),
        Q!("    eor             " "x9, x9, x4"),
        Q!("    sbc             " "x1, x1, x10"),
        Q!("    adds            " "x15, x8, x3"),
        Q!("    adcs            " "x3, x16, x10"),
        Q!("    mul             " "x16, x11, x6"),
        Q!("    adcs            " "x8, x13, x7"),
        Q!("    eor             " "x13, x12, x4"),
        Q!("    adc             " "x10, x1, xzr"),
        Q!("    cmn             " "x4, #0x1"),
        Q!("    umulh           " "x6, x11, x6"),
        Q!("    adcs            " "x11, x13, xzr"),
        Q!("    adcs            " "x1, x9, xzr"),
        Q!("    lsl             " "x13, x15, #32"),
        Q!("    subs            " "x12, x15, x13"),
        Q!("    lsr             " "x7, x15, #32"),
        Q!("    sbc             " "x15, x15, x7"),
        Q!("    adds            " "x21, x3, x13"),
        Q!("    adcs            " "x22, x8, x7"),
        Q!("    umulh           " "x8, x14, x11"),
        Q!("    umull           " "v21.2d, v0.2s, v1.2s"),
        Q!("    adcs            " "x23, x10, x12"),
        Q!("    umull           " "v3.2d, v0.2s, v16.2s"),
        Q!("    adc             " "x24, x15, xzr"),
        Q!("    rev64           " "v24.4s, v20.4s"),
        Q!("    movi            " "v2.2d, #0xffffffff"),
        Q!("    mul             " "x10, x14, x11"),
        Q!("    mul             " "v4.4s, v24.4s, v28.4s"),
        Q!("    subs            " "x13, x14, x5"),
        Q!("    uzp2            " "v19.4s, v28.4s, v28.4s"),
        Q!("    csetm           " "x15, cc"),
        Q!("    usra            " "v3.2d, v21.2d, #32"),
        Q!("    mul             " "x7, x5, x1"),
        Q!("    umull           " "v21.2d, v19.2s, v16.2s"),
        Q!("    cneg            " "x13, x13, cc"),
        Q!("    uaddlp          " "v5.2d, v4.4s"),
        Q!("    subs            " "x11, x1, x11"),
        Q!("    and             " "v16.16b, v3.16b, v2.16b"),
        Q!("    umulh           " "x5, x5, x1"),
        Q!("    shl             " "v24.2d, v5.2d, #32"),
        Q!("    cneg            " "x11, x11, cc"),
        Q!("    umlal           " "v16.2d, v19.2s, v1.2s"),
        Q!("    cinv            " "x12, x15, cc"),
        Q!("    umlal           " "v24.2d, v0.2s, v1.2s"),
        Q!("    adds            " "x15, x10, x7"),
        Q!("    mul             " "x14, x13, x11"),
        Q!("    eor             " "x1, x6, x2"),
        Q!("    adcs            " "x6, x8, x5"),
        Q!("    usra            " "v21.2d, v3.2d, #32"),
        Q!("    adcs            " "x9, x5, xzr"),
        Q!("    umulh           " "x11, x13, x11"),
        Q!("    adds            " "x15, x8, x15"),
        Q!("    adcs            " "x7, x7, x6"),
        Q!("    eor             " "x8, x14, x12"),
        Q!("    usra            " "v21.2d, v16.2d, #32"),
        Q!("    adcs            " "x13, x9, xzr"),
        Q!("    cmn             " "x12, #0x1"),
        Q!("    mov             " "x9, v24.d[1]"),
        Q!("    adcs            " "x14, x15, x8"),
        Q!("    eor             " "x6, x11, x12"),
        Q!("    adcs            " "x6, x7, x6"),
        Q!("    mov             " "x5, v24.d[0]"),
        Q!("    mov             " "x11, v21.d[1]"),
        Q!("    mov             " "x7, v21.d[0]"),
        Q!("    adc             " "x3, x13, x12"),
        Q!("    adds            " "x12, x5, x9"),
        Q!("    adcs            " "x13, x7, x11"),
        Q!("    adcs            " "x11, x11, xzr"),
        Q!("    adds            " "x12, x7, x12"),
        Q!("    eor             " "x16, x16, x2"),
        Q!("    adcs            " "x7, x9, x13"),
        Q!("    adcs            " "x11, x11, xzr"),
        Q!("    cmn             " "x2, #0x1"),
        Q!("    adcs            " "x16, x12, x16"),
        Q!("    adcs            " "x1, x7, x1"),
        Q!("    adc             " "x2, x11, x2"),
        Q!("    adds            " "x7, x5, x21"),
        Q!("    adcs            " "x15, x16, x22"),
        Q!("    eor             " "x5, x17, x4"),
        Q!("    adcs            " "x9, x1, x23"),
        Q!("    eor             " "x1, x10, x5"),
        Q!("    adcs            " "x16, x2, x24"),
        Q!("    adc             " "x2, xzr, xzr"),
        Q!("    cmn             " "x5, #0x1"),
        Q!("    eor             " "x13, x14, x5"),
        Q!("    adcs            " "x14, x1, x7"),
        Q!("    eor             " "x1, x6, x5"),
        Q!("    adcs            " "x6, x13, x15"),
        Q!("    adcs            " "x10, x1, x9"),
        Q!("    eor             " "x4, x3, x5"),
        Q!("    mov             " "x1, #0xffffffff"),
        Q!("    adcs            " "x8, x4, x16"),
        Q!("    lsr             " "x13, x14, #32"),
        Q!("    adcs            " "x17, x2, x5"),
        Q!("    adcs            " "x11, x5, xzr"),
        Q!("    adc             " "x4, x5, xzr"),
        Q!("    adds            " "x12, x10, x7"),
        Q!("    adcs            " "x7, x8, x15"),
        Q!("    adcs            " "x5, x17, x9"),
        Q!("    adcs            " "x9, x11, x16"),
        Q!("    lsl             " "x11, x14, #32"),
        Q!("    adc             " "x10, x4, x2"),
        Q!("    subs            " "x17, x14, x11"),
        Q!("    sbc             " "x4, x14, x13"),
        Q!("    adds            " "x11, x6, x11"),
        Q!("    adcs            " "x12, x12, x13"),
        Q!("    lsl             " "x15, x11, #32"),
        Q!("    adcs            " "x17, x7, x17"),
        Q!("    lsr             " "x7, x11, #32"),
        Q!("    adc             " "x13, x4, xzr"),
        Q!("    subs            " "x4, x11, x15"),
        Q!("    sbc             " "x11, x11, x7"),
        Q!("    adds            " "x8, x12, x15"),
        Q!("    adcs            " "x15, x17, x7"),
        Q!("    adcs            " "x4, x13, x4"),
        Q!("    adc             " "x11, x11, xzr"),
        Q!("    adds            " "x7, x5, x4"),
        Q!("    adcs            " "x17, x9, x11"),
        Q!("    adc             " "x13, x10, xzr"),
        Q!("    add             " "x12, x13, #0x1"),
        Q!("    neg             " "x11, x12"),
        Q!("    lsl             " "x4, x12, #32"),
        Q!("    adds            " "x17, x17, x4"),
        Q!("    sub             " "x4, x4, #0x1"),
        Q!("    adc             " "x13, x13, xzr"),
        Q!("    subs            " "x11, x8, x11"),
        Q!("    sbcs            " "x4, x15, x4"),
        Q!("    sbcs            " "x7, x7, xzr"),
        Q!("    sbcs            " "x17, x17, x12"),
        Q!("    sbcs            " "x13, x13, x12"),
        Q!("    mov             " "x12, #0xffffffff00000001"),
        Q!("    adds            " "x21, x11, x13"),
        Q!("    and             " "x1, x1, x13"),
        Q!("    adcs            " "x22, x4, x1"),
        Q!("    and             " "x1, x12, x13"),
        Q!("    stp             " "x21, x22, [sp, #96]"),
        Q!("    adcs            " "x23, x7, xzr"),
        Q!("    adc             " "x24, x17, x1"),
        Q!("    stp             " "x23, x24, [sp, #112]"),
        Q!("    ldp             " "x4, x5, [x20, #32]"),
        Q!("    ldp             " "x8, x9, [x20, #64]"),
        Q!("    adds            " "x4, x4, x8"),
        Q!("    adcs            " "x5, x5, x9"),
        Q!("    ldp             " "x6, x7, [x20, #48]"),
        Q!("    ldp             " "x10, x11, [x20, #80]"),
        Q!("    adcs            " "x6, x6, x10"),
        Q!("    adcs            " "x7, x7, x11"),
        Q!("    adc             " "x3, xzr, xzr"),
        Q!("    adds            " "x8, x4, #0x1"),
        Q!("    mov             " "x9, #0xffffffff"),
        Q!("    sbcs            " "x9, x5, x9"),
        Q!("    sbcs            " "x10, x6, xzr"),
        Q!("    mov             " "x11, #0xffffffff00000001"),
        Q!("    sbcs            " "x11, x7, x11"),
        Q!("    sbcs            " "x3, x3, xzr"),
        Q!("    csel            " "x4, x4, x8, cc"),
        Q!("    csel            " "x5, x5, x9, cc"),
        Q!("    csel            " "x6, x6, x10, cc"),
        Q!("    csel            " "x7, x7, x11, cc"),
        Q!("    stp             " "x4, x5, [sp, #64]"),
        Q!("    stp             " "x6, x7, [sp, #80]"),
        Q!("    ldr             " "q20, [sp, #32]"),
        Q!("    ldp             " "x7, x17, [x20, #0]"),
        Q!("    ldr             " "q0, [x20, #0]"),
        Q!("    ldp             " "x6, x10, [sp, #32]"),
        Q!("    ldp             " "x11, x15, [x20, #16]"),
        Q!("    rev64           " "v16.4s, v20.4s"),
        Q!("    subs            " "x4, x7, x17"),
        Q!("    csetm           " "x3, cc"),
        Q!("    cneg            " "x13, x4, cc"),
        Q!("    mul             " "v16.4s, v16.4s, v0.4s"),
        Q!("    umulh           " "x12, x17, x10"),
        Q!("    uzp1            " "v28.4s, v20.4s, v0.4s"),
        Q!("    subs            " "x14, x11, x7"),
        Q!("    ldr             " "q20, [sp, #48]"),
        Q!("    sbcs            " "x5, x15, x17"),
        Q!("    ngc             " "x17, xzr"),
        Q!("    subs            " "x8, x11, x15"),
        Q!("    uaddlp          " "v27.2d, v16.4s"),
        Q!("    umulh           " "x4, x7, x6"),
        Q!("    uzp1            " "v21.4s, v0.4s, v0.4s"),
        Q!("    cneg            " "x11, x8, cc"),
        Q!("    shl             " "v17.2d, v27.2d, #32"),
        Q!("    csetm           " "x15, cc"),
        Q!("    subs            " "x9, x10, x6"),
        Q!("    eor             " "x7, x14, x17"),
        Q!("    umlal           " "v17.2d, v21.2s, v28.2s"),
        Q!("    cneg            " "x8, x9, cc"),
        Q!("    cinv            " "x9, x3, cc"),
        Q!("    cmn             " "x17, #0x1"),
        Q!("    ldr             " "q28, [x20, #16]"),
        Q!("    adcs            " "x14, x7, xzr"),
        Q!("    mul             " "x7, x13, x8"),
        Q!("    eor             " "x1, x5, x17"),
        Q!("    adcs            " "x5, x1, xzr"),
        Q!("    xtn             " "v1.2s, v20.2d"),
        Q!("    mov             " "x1, v17.d[0]"),
        Q!("    mov             " "x3, v17.d[1]"),
        Q!("    uzp2            " "v16.4s, v20.4s, v20.4s"),
        Q!("    umulh           " "x16, x13, x8"),
        Q!("    eor             " "x13, x7, x9"),
        Q!("    adds            " "x8, x1, x3"),
        Q!("    adcs            " "x7, x4, x12"),
        Q!("    xtn             " "v0.2s, v28.2d"),
        Q!("    adcs            " "x12, x12, xzr"),
        Q!("    adds            " "x8, x4, x8"),
        Q!("    adcs            " "x3, x3, x7"),
        Q!("    ldp             " "x7, x2, [sp, #48]"),
        Q!("    adcs            " "x12, x12, xzr"),
        Q!("    cmn             " "x9, #0x1"),
        Q!("    adcs            " "x8, x8, x13"),
        Q!("    eor             " "x13, x16, x9"),
        Q!("    adcs            " "x16, x3, x13"),
        Q!("    lsl             " "x3, x1, #32"),
        Q!("    adc             " "x13, x12, x9"),
        Q!("    subs            " "x12, x6, x7"),
        Q!("    sbcs            " "x9, x10, x2"),
        Q!("    lsr             " "x10, x1, #32"),
        Q!("    ngc             " "x4, xzr"),
        Q!("    subs            " "x6, x2, x7"),
        Q!("    cinv            " "x2, x15, cc"),
        Q!("    cneg            " "x6, x6, cc"),
        Q!("    subs            " "x7, x1, x3"),
        Q!("    eor             " "x9, x9, x4"),
        Q!("    sbc             " "x1, x1, x10"),
        Q!("    adds            " "x15, x8, x3"),
        Q!("    adcs            " "x3, x16, x10"),
        Q!("    mul             " "x16, x11, x6"),
        Q!("    adcs            " "x8, x13, x7"),
        Q!("    eor             " "x13, x12, x4"),
        Q!("    adc             " "x10, x1, xzr"),
        Q!("    cmn             " "x4, #0x1"),
        Q!("    umulh           " "x6, x11, x6"),
        Q!("    adcs            " "x11, x13, xzr"),
        Q!("    adcs            " "x1, x9, xzr"),
        Q!("    lsl             " "x13, x15, #32"),
        Q!("    subs            " "x12, x15, x13"),
        Q!("    lsr             " "x7, x15, #32"),
        Q!("    sbc             " "x15, x15, x7"),
        Q!("    adds            " "x20, x3, x13"),
        Q!("    adcs            " "x25, x8, x7"),
        Q!("    umulh           " "x8, x14, x11"),
        Q!("    umull           " "v21.2d, v0.2s, v1.2s"),
        Q!("    adcs            " "x26, x10, x12"),
        Q!("    umull           " "v3.2d, v0.2s, v16.2s"),
        Q!("    adc             " "x27, x15, xzr"),
        Q!("    rev64           " "v24.4s, v20.4s"),
        Q!("    movi            " "v2.2d, #0xffffffff"),
        Q!("    mul             " "x10, x14, x11"),
        Q!("    mul             " "v4.4s, v24.4s, v28.4s"),
        Q!("    subs            " "x13, x14, x5"),
        Q!("    uzp2            " "v19.4s, v28.4s, v28.4s"),
        Q!("    csetm           " "x15, cc"),
        Q!("    usra            " "v3.2d, v21.2d, #32"),
        Q!("    mul             " "x7, x5, x1"),
        Q!("    umull           " "v21.2d, v19.2s, v16.2s"),
        Q!("    cneg            " "x13, x13, cc"),
        Q!("    uaddlp          " "v5.2d, v4.4s"),
        Q!("    subs            " "x11, x1, x11"),
        Q!("    and             " "v16.16b, v3.16b, v2.16b"),
        Q!("    umulh           " "x5, x5, x1"),
        Q!("    shl             " "v24.2d, v5.2d, #32"),
        Q!("    cneg            " "x11, x11, cc"),
        Q!("    umlal           " "v16.2d, v19.2s, v1.2s"),
        Q!("    cinv            " "x12, x15, cc"),
        Q!("    umlal           " "v24.2d, v0.2s, v1.2s"),
        Q!("    adds            " "x15, x10, x7"),
        Q!("    mul             " "x14, x13, x11"),
        Q!("    eor             " "x1, x6, x2"),
        Q!("    adcs            " "x6, x8, x5"),
        Q!("    usra            " "v21.2d, v3.2d, #32"),
        Q!("    adcs            " "x9, x5, xzr"),
        Q!("    umulh           " "x11, x13, x11"),
        Q!("    adds            " "x15, x8, x15"),
        Q!("    adcs            " "x7, x7, x6"),
        Q!("    eor             " "x8, x14, x12"),
        Q!("    usra            " "v21.2d, v16.2d, #32"),
        Q!("    adcs            " "x13, x9, xzr"),
        Q!("    cmn             " "x12, #0x1"),
        Q!("    mov             " "x9, v24.d[1]"),
        Q!("    adcs            " "x14, x15, x8"),
        Q!("    eor             " "x6, x11, x12"),
        Q!("    adcs            " "x6, x7, x6"),
        Q!("    mov             " "x5, v24.d[0]"),
        Q!("    mov             " "x11, v21.d[1]"),
        Q!("    mov             " "x7, v21.d[0]"),
        Q!("    adc             " "x3, x13, x12"),
        Q!("    adds            " "x12, x5, x9"),
        Q!("    adcs            " "x13, x7, x11"),
        Q!("    adcs            " "x11, x11, xzr"),
        Q!("    adds            " "x12, x7, x12"),
        Q!("    eor             " "x16, x16, x2"),
        Q!("    adcs            " "x7, x9, x13"),
        Q!("    adcs            " "x11, x11, xzr"),
        Q!("    cmn             " "x2, #0x1"),
        Q!("    adcs            " "x16, x12, x16"),
        Q!("    adcs            " "x1, x7, x1"),
        Q!("    adc             " "x2, x11, x2"),
        Q!("    adds            " "x7, x5, x20"),
        Q!("    adcs            " "x15, x16, x25"),
        Q!("    eor             " "x5, x17, x4"),
        Q!("    adcs            " "x9, x1, x26"),
        Q!("    eor             " "x1, x10, x5"),
        Q!("    adcs            " "x16, x2, x27"),
        Q!("    adc             " "x2, xzr, xzr"),
        Q!("    cmn             " "x5, #0x1"),
        Q!("    eor             " "x13, x14, x5"),
        Q!("    adcs            " "x14, x1, x7"),
        Q!("    eor             " "x1, x6, x5"),
        Q!("    adcs            " "x6, x13, x15"),
        Q!("    adcs            " "x10, x1, x9"),
        Q!("    eor             " "x4, x3, x5"),
        Q!("    mov             " "x1, #0xffffffff"),
        Q!("    adcs            " "x8, x4, x16"),
        Q!("    lsr             " "x13, x14, #32"),
        Q!("    adcs            " "x17, x2, x5"),
        Q!("    adcs            " "x11, x5, xzr"),
        Q!("    adc             " "x4, x5, xzr"),
        Q!("    adds            " "x12, x10, x7"),
        Q!("    adcs            " "x7, x8, x15"),
        Q!("    adcs            " "x5, x17, x9"),
        Q!("    adcs            " "x9, x11, x16"),
        Q!("    lsl             " "x11, x14, #32"),
        Q!("    adc             " "x10, x4, x2"),
        Q!("    subs            " "x17, x14, x11"),
        Q!("    sbc             " "x4, x14, x13"),
        Q!("    adds            " "x11, x6, x11"),
        Q!("    adcs            " "x12, x12, x13"),
        Q!("    lsl             " "x15, x11, #32"),
        Q!("    adcs            " "x17, x7, x17"),
        Q!("    lsr             " "x7, x11, #32"),
        Q!("    adc             " "x13, x4, xzr"),
        Q!("    subs            " "x4, x11, x15"),
        Q!("    sbc             " "x11, x11, x7"),
        Q!("    adds            " "x8, x12, x15"),
        Q!("    adcs            " "x15, x17, x7"),
        Q!("    adcs            " "x4, x13, x4"),
        Q!("    adc             " "x11, x11, xzr"),
        Q!("    adds            " "x7, x5, x4"),
        Q!("    adcs            " "x17, x9, x11"),
        Q!("    adc             " "x13, x10, xzr"),
        Q!("    add             " "x12, x13, #0x1"),
        Q!("    neg             " "x11, x12"),
        Q!("    lsl             " "x4, x12, #32"),
        Q!("    adds            " "x17, x17, x4"),
        Q!("    sub             " "x4, x4, #0x1"),
        Q!("    adc             " "x13, x13, xzr"),
        Q!("    subs            " "x11, x8, x11"),
        Q!("    sbcs            " "x4, x15, x4"),
        Q!("    sbcs            " "x7, x7, xzr"),
        Q!("    sbcs            " "x17, x17, x12"),
        Q!("    sbcs            " "x13, x13, x12"),
        Q!("    mov             " "x12, #0xffffffff00000001"),
        Q!("    adds            " "x20, x11, x13"),
        Q!("    and             " "x1, x1, x13"),
        Q!("    adcs            " "x25, x4, x1"),
        Q!("    and             " "x1, x12, x13"),
        Q!("    stp             " "x20, x25, [sp, #128]"),
        Q!("    adcs            " "x4, x7, xzr"),
        Q!("    adc             " "x1, x17, x1"),
        Q!("    stp             " "x4, x1, [sp, #144]"),
        Q!("    ldr             " "q19, [sp, #96]"),
        Q!("    ldr             " "q23, [sp, #112]"),
        Q!("    ldr             " "q0, [sp, #96]"),
        Q!("    uzp2            " "v29.4s, v19.4s, v19.4s"),
        Q!("    xtn             " "v4.2s, v19.2d"),
        Q!("    umulh           " "x8, x21, x22"),
        Q!("    rev64           " "v20.4s, v23.4s"),
        Q!("    umull           " "v16.2d, v19.2s, v19.2s"),
        Q!("    umull           " "v1.2d, v29.2s, v4.2s"),
        Q!("    mul             " "v20.4s, v20.4s, v0.4s"),
        Q!("    subs            " "x14, x21, x22"),
        Q!("    umulh           " "x15, x21, x23"),
        Q!("    mov             " "x16, v16.d[1]"),
        Q!("    umull2          " "v4.2d, v19.4s, v19.4s"),
        Q!("    mov             " "x4, v16.d[0]"),
        Q!("    uzp1            " "v17.4s, v23.4s, v0.4s"),
        Q!("    uaddlp          " "v19.2d, v20.4s"),
        Q!("    lsr             " "x7, x8, #63"),
        Q!("    mul             " "x11, x21, x22"),
        Q!("    mov             " "x12, v1.d[0]"),
        Q!("    csetm           " "x5, cc"),
        Q!("    cneg            " "x6, x14, cc"),
        Q!("    mov             " "x3, v4.d[1]"),
        Q!("    mov             " "x14, v4.d[0]"),
        Q!("    subs            " "x2, x24, x23"),
        Q!("    mov             " "x9, v1.d[1]"),
        Q!("    cneg            " "x17, x2, cc"),
        Q!("    cinv            " "x2, x5, cc"),
        Q!("    adds            " "x5, x4, x12, lsl #33"),
        Q!("    extr            " "x4, x8, x11, #63"),
        Q!("    lsr             " "x8, x12, #31"),
        Q!("    uzp1            " "v20.4s, v0.4s, v0.4s"),
        Q!("    shl             " "v19.2d, v19.2d, #32"),
        Q!("    adc             " "x16, x16, x8"),
        Q!("    adds            " "x8, x14, x9, lsl #33"),
        Q!("    lsr             " "x14, x9, #31"),
        Q!("    lsl             " "x9, x5, #32"),
        Q!("    umlal           " "v19.2d, v20.2s, v17.2s"),
        Q!("    adc             " "x14, x3, x14"),
        Q!("    adds            " "x16, x16, x11, lsl #1"),
        Q!("    lsr             " "x3, x5, #32"),
        Q!("    umulh           " "x12, x6, x17"),
        Q!("    adcs            " "x4, x8, x4"),
        Q!("    adc             " "x11, x14, x7"),
        Q!("    subs            " "x8, x5, x9"),
        Q!("    sbc             " "x5, x5, x3"),
        Q!("    adds            " "x16, x16, x9"),
        Q!("    mov             " "x14, v19.d[0]"),
        Q!("    mul             " "x17, x6, x17"),
        Q!("    adcs            " "x3, x4, x3"),
        Q!("    lsl             " "x7, x16, #32"),
        Q!("    umulh           " "x13, x22, x24"),
        Q!("    adcs            " "x11, x11, x8"),
        Q!("    lsr             " "x8, x16, #32"),
        Q!("    adc             " "x5, x5, xzr"),
        Q!("    subs            " "x9, x16, x7"),
        Q!("    sbc             " "x16, x16, x8"),
        Q!("    adds            " "x7, x3, x7"),
        Q!("    mov             " "x3, v19.d[1]"),
        Q!("    adcs            " "x6, x11, x8"),
        Q!("    umulh           " "x11, x23, x24"),
        Q!("    adcs            " "x5, x5, x9"),
        Q!("    eor             " "x8, x12, x2"),
        Q!("    adc             " "x9, x16, xzr"),
        Q!("    adds            " "x16, x14, x15"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x12, x16, x3"),
        Q!("    eor             " "x16, x17, x2"),
        Q!("    mul             " "x4, x23, x24"),
        Q!("    adcs            " "x15, x15, x13"),
        Q!("    adc             " "x17, x13, xzr"),
        Q!("    adds            " "x15, x15, x3"),
        Q!("    adc             " "x3, x17, xzr"),
        Q!("    cmn             " "x2, #0x1"),
        Q!("    mul             " "x17, x24, x24"),
        Q!("    adcs            " "x12, x12, x16"),
        Q!("    adcs            " "x16, x15, x8"),
        Q!("    umulh           " "x10, x24, x24"),
        Q!("    adc             " "x2, x3, x2"),
        Q!("    adds            " "x14, x14, x14"),
        Q!("    adcs            " "x12, x12, x12"),
        Q!("    adcs            " "x16, x16, x16"),
        Q!("    adcs            " "x2, x2, x2"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    adds            " "x14, x14, x7"),
        Q!("    mul             " "x3, x23, x23"),
        Q!("    adcs            " "x12, x12, x6"),
        Q!("    lsr             " "x7, x14, #32"),
        Q!("    adcs            " "x16, x16, x5"),
        Q!("    lsl             " "x5, x14, #32"),
        Q!("    umulh           " "x13, x23, x23"),
        Q!("    adcs            " "x2, x2, x9"),
        Q!("    mov             " "x6, #0xffffffff"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x8, x4, x4"),
        Q!("    adcs            " "x1, x11, x11"),
        Q!("    mov             " "x11, #0xffffffff00000001"),
        Q!("    adc             " "x4, xzr, xzr"),
        Q!("    subs            " "x9, x14, x5"),
        Q!("    sbc             " "x14, x14, x7"),
        Q!("    adds            " "x12, x12, x5"),
        Q!("    adcs            " "x16, x16, x7"),
        Q!("    lsl             " "x5, x12, #32"),
        Q!("    lsr             " "x7, x12, #32"),
        Q!("    adcs            " "x2, x2, x9"),
        Q!("    adcs            " "x14, x15, x14"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    subs            " "x9, x12, x5"),
        Q!("    sbc             " "x12, x12, x7"),
        Q!("    adds            " "x16, x16, x5"),
        Q!("    adcs            " "x2, x2, x7"),
        Q!("    adcs            " "x14, x14, x9"),
        Q!("    adcs            " "x12, x15, x12"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    adds            " "x16, x16, x3"),
        Q!("    adcs            " "x2, x2, x13"),
        Q!("    adcs            " "x14, x14, x17"),
        Q!("    adcs            " "x12, x12, x10"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x2, x2, x8"),
        Q!("    adcs            " "x14, x14, x1"),
        Q!("    adcs            " "x12, x12, x4"),
        Q!("    adcs            " "x15, x15, xzr"),
        Q!("    adds            " "x3, x16, #0x1"),
        Q!("    sbcs            " "x5, x2, x6"),
        Q!("    sbcs            " "x8, x14, xzr"),
        Q!("    sbcs            " "x11, x12, x11"),
        Q!("    sbcs            " "xzr, x15, xzr"),
        Q!("    csel            " "x21, x3, x16, cs"),
        Q!("    csel            " "x22, x8, x14, cs"),
        Q!("    csel            " "x23, x11, x12, cs"),
        Q!("    csel            " "x24, x5, x2, cs"),
        Q!("    ldr             " "q19, [sp, #64]"),
        Q!("    ldp             " "x9, x13, [sp, #64]"),
        Q!("    ldr             " "q23, [sp, #80]"),
        Q!("    ldr             " "q0, [sp, #64]"),
        Q!("    ldp             " "x1, x10, [sp, #80]"),
        Q!("    uzp2            " "v29.4s, v19.4s, v19.4s"),
        Q!("    xtn             " "v4.2s, v19.2d"),
        Q!("    umulh           " "x8, x9, x13"),
        Q!("    rev64           " "v20.4s, v23.4s"),
        Q!("    umull           " "v16.2d, v19.2s, v19.2s"),
        Q!("    umull           " "v1.2d, v29.2s, v4.2s"),
        Q!("    mul             " "v20.4s, v20.4s, v0.4s"),
        Q!("    subs            " "x14, x9, x13"),
        Q!("    umulh           " "x15, x9, x1"),
        Q!("    mov             " "x16, v16.d[1]"),
        Q!("    umull2          " "v4.2d, v19.4s, v19.4s"),
        Q!("    mov             " "x4, v16.d[0]"),
        Q!("    uzp1            " "v17.4s, v23.4s, v0.4s"),
        Q!("    uaddlp          " "v19.2d, v20.4s"),
        Q!("    lsr             " "x7, x8, #63"),
        Q!("    mul             " "x11, x9, x13"),
        Q!("    mov             " "x12, v1.d[0]"),
        Q!("    csetm           " "x5, cc"),
        Q!("    cneg            " "x6, x14, cc"),
        Q!("    mov             " "x3, v4.d[1]"),
        Q!("    mov             " "x14, v4.d[0]"),
        Q!("    subs            " "x2, x10, x1"),
        Q!("    mov             " "x9, v1.d[1]"),
        Q!("    cneg            " "x17, x2, cc"),
        Q!("    cinv            " "x2, x5, cc"),
        Q!("    adds            " "x5, x4, x12, lsl #33"),
        Q!("    extr            " "x4, x8, x11, #63"),
        Q!("    lsr             " "x8, x12, #31"),
        Q!("    uzp1            " "v20.4s, v0.4s, v0.4s"),
        Q!("    shl             " "v19.2d, v19.2d, #32"),
        Q!("    adc             " "x16, x16, x8"),
        Q!("    adds            " "x8, x14, x9, lsl #33"),
        Q!("    lsr             " "x14, x9, #31"),
        Q!("    lsl             " "x9, x5, #32"),
        Q!("    umlal           " "v19.2d, v20.2s, v17.2s"),
        Q!("    adc             " "x14, x3, x14"),
        Q!("    adds            " "x16, x16, x11, lsl #1"),
        Q!("    lsr             " "x3, x5, #32"),
        Q!("    umulh           " "x12, x6, x17"),
        Q!("    adcs            " "x4, x8, x4"),
        Q!("    adc             " "x11, x14, x7"),
        Q!("    subs            " "x8, x5, x9"),
        Q!("    sbc             " "x5, x5, x3"),
        Q!("    adds            " "x16, x16, x9"),
        Q!("    mov             " "x14, v19.d[0]"),
        Q!("    mul             " "x17, x6, x17"),
        Q!("    adcs            " "x3, x4, x3"),
        Q!("    lsl             " "x7, x16, #32"),
        Q!("    umulh           " "x13, x13, x10"),
        Q!("    adcs            " "x11, x11, x8"),
        Q!("    lsr             " "x8, x16, #32"),
        Q!("    adc             " "x5, x5, xzr"),
        Q!("    subs            " "x9, x16, x7"),
        Q!("    sbc             " "x16, x16, x8"),
        Q!("    adds            " "x7, x3, x7"),
        Q!("    mov             " "x3, v19.d[1]"),
        Q!("    adcs            " "x6, x11, x8"),
        Q!("    umulh           " "x11, x1, x10"),
        Q!("    adcs            " "x5, x5, x9"),
        Q!("    eor             " "x8, x12, x2"),
        Q!("    adc             " "x9, x16, xzr"),
        Q!("    adds            " "x16, x14, x15"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x12, x16, x3"),
        Q!("    eor             " "x16, x17, x2"),
        Q!("    mul             " "x4, x1, x10"),
        Q!("    adcs            " "x15, x15, x13"),
        Q!("    adc             " "x17, x13, xzr"),
        Q!("    adds            " "x15, x15, x3"),
        Q!("    adc             " "x3, x17, xzr"),
        Q!("    cmn             " "x2, #0x1"),
        Q!("    mul             " "x17, x10, x10"),
        Q!("    adcs            " "x12, x12, x16"),
        Q!("    adcs            " "x16, x15, x8"),
        Q!("    umulh           " "x10, x10, x10"),
        Q!("    adc             " "x2, x3, x2"),
        Q!("    adds            " "x14, x14, x14"),
        Q!("    adcs            " "x12, x12, x12"),
        Q!("    adcs            " "x16, x16, x16"),
        Q!("    adcs            " "x2, x2, x2"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    adds            " "x14, x14, x7"),
        Q!("    mul             " "x3, x1, x1"),
        Q!("    adcs            " "x12, x12, x6"),
        Q!("    lsr             " "x7, x14, #32"),
        Q!("    adcs            " "x16, x16, x5"),
        Q!("    lsl             " "x5, x14, #32"),
        Q!("    umulh           " "x13, x1, x1"),
        Q!("    adcs            " "x2, x2, x9"),
        Q!("    mov             " "x6, #0xffffffff"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x8, x4, x4"),
        Q!("    adcs            " "x1, x11, x11"),
        Q!("    mov             " "x11, #0xffffffff00000001"),
        Q!("    adc             " "x4, xzr, xzr"),
        Q!("    subs            " "x9, x14, x5"),
        Q!("    sbc             " "x14, x14, x7"),
        Q!("    adds            " "x12, x12, x5"),
        Q!("    adcs            " "x16, x16, x7"),
        Q!("    lsl             " "x5, x12, #32"),
        Q!("    lsr             " "x7, x12, #32"),
        Q!("    adcs            " "x2, x2, x9"),
        Q!("    adcs            " "x14, x15, x14"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    subs            " "x9, x12, x5"),
        Q!("    sbc             " "x12, x12, x7"),
        Q!("    adds            " "x16, x16, x5"),
        Q!("    adcs            " "x2, x2, x7"),
        Q!("    adcs            " "x14, x14, x9"),
        Q!("    adcs            " "x12, x15, x12"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    adds            " "x16, x16, x3"),
        Q!("    adcs            " "x2, x2, x13"),
        Q!("    adcs            " "x14, x14, x17"),
        Q!("    adcs            " "x12, x12, x10"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x2, x2, x8"),
        Q!("    adcs            " "x14, x14, x1"),
        Q!("    adcs            " "x12, x12, x4"),
        Q!("    adcs            " "x15, x15, xzr"),
        Q!("    adds            " "x3, x16, #0x1"),
        Q!("    sbcs            " "x5, x2, x6"),
        Q!("    sbcs            " "x8, x14, xzr"),
        Q!("    sbcs            " "x11, x12, x11"),
        Q!("    sbcs            " "xzr, x15, xzr"),
        Q!("    csel            " "x13, x3, x16, cs"),
        Q!("    csel            " "x14, x8, x14, cs"),
        Q!("    csel            " "x15, x11, x12, cs"),
        Q!("    csel            " "x26, x5, x2, cs"),
        Q!("    mov             " "x1, #0x9"),
        Q!("    mov             " "x2, #0xffffffffffffffff"),
        Q!("    subs            " "x9, x2, x21"),
        Q!("    mov             " "x2, #0xffffffff"),
        Q!("    sbcs            " "x10, x2, x24"),
        Q!("    ngcs            " "x11, x22"),
        Q!("    mov             " "x2, #0xffffffff00000001"),
        Q!("    sbc             " "x12, x2, x23"),
        Q!("    mul             " "x3, x1, x9"),
        Q!("    mul             " "x4, x1, x10"),
        Q!("    mul             " "x5, x1, x11"),
        Q!("    mul             " "x6, x1, x12"),
        Q!("    umulh           " "x9, x1, x9"),
        Q!("    umulh           " "x10, x1, x10"),
        Q!("    umulh           " "x11, x1, x11"),
        Q!("    umulh           " "x7, x1, x12"),
        Q!("    adds            " "x4, x4, x9"),
        Q!("    adcs            " "x5, x5, x10"),
        Q!("    adcs            " "x6, x6, x11"),
        Q!("    adc             " "x7, x7, xzr"),
        Q!("    mov             " "x1, #0xc"),
        Q!("    mul             " "x8, x20, x1"),
        Q!("    umulh           " "x9, x20, x1"),
        Q!("    adds            " "x3, x3, x8"),
        Q!("    mul             " "x8, x25, x1"),
        Q!("    umulh           " "x10, x25, x1"),
        Q!("    adcs            " "x4, x4, x8"),
        Q!("    ldp             " "x11, x12, [sp, #144]"),
        Q!("    mul             " "x8, x11, x1"),
        Q!("    umulh           " "x11, x11, x1"),
        Q!("    adcs            " "x5, x5, x8"),
        Q!("    mul             " "x8, x12, x1"),
        Q!("    umulh           " "x12, x12, x1"),
        Q!("    adcs            " "x6, x6, x8"),
        Q!("    adc             " "x7, x7, xzr"),
        Q!("    adds            " "x4, x4, x9"),
        Q!("    adcs            " "x5, x5, x10"),
        Q!("    adcs            " "x6, x6, x11"),
        Q!("    adc             " "x7, x7, x12"),
        Q!("    add             " "x8, x7, #0x1"),
        Q!("    lsl             " "x10, x8, #32"),
        Q!("    adds            " "x6, x6, x10"),
        Q!("    adc             " "x7, x7, xzr"),
        Q!("    neg             " "x9, x8"),
        Q!("    sub             " "x10, x10, #0x1"),
        Q!("    subs            " "x3, x3, x9"),
        Q!("    sbcs            " "x4, x4, x10"),
        Q!("    sbcs            " "x5, x5, xzr"),
        Q!("    sbcs            " "x6, x6, x8"),
        Q!("    sbc             " "x8, x7, x8"),
        Q!("    adds            " "x20, x3, x8"),
        Q!("    and             " "x9, x8, #0xffffffff"),
        Q!("    adcs            " "x21, x4, x9"),
        Q!("    adcs            " "x22, x5, xzr"),
        Q!("    neg             " "x10, x9"),
        Q!("    adc             " "x23, x6, x10"),
        Q!("    stp             " "x20, x21, [sp, #160]"),
        Q!("    stp             " "x22, x23, [sp, #176]"),
        Q!("    mov             " "x2, sp"),
        Q!("    ldp             " "x4, x3, [x2]"),
        Q!("    subs            " "x5, x13, x4"),
        Q!("    sbcs            " "x6, x26, x3"),
        Q!("    ldp             " "x4, x3, [x2, #16]"),
        Q!("    sbcs            " "x7, x14, x4"),
        Q!("    sbcs            " "x8, x15, x3"),
        Q!("    csetm           " "x3, cc"),
        Q!("    adds            " "x5, x5, x3"),
        Q!("    and             " "x4, x3, #0xffffffff"),
        Q!("    adcs            " "x6, x6, x4"),
        Q!("    adcs            " "x7, x7, xzr"),
        Q!("    and             " "x4, x3, #0xffffffff00000001"),
        Q!("    adc             " "x8, x8, x4"),
        Q!("    stp             " "x5, x6, [sp, #64]"),
        Q!("    stp             " "x7, x8, [sp, #80]"),
        Q!("    mov             " "x0, sp"),
        Q!("    ldr             " "q19, [sp, #32]"),
        Q!("    ldp             " "x9, x13, [sp, #32]"),
        Q!("    ldr             " "q23, [sp, #48]"),
        Q!("    ldr             " "q0, [sp, #32]"),
        Q!("    ldp             " "x1, x10, [sp, #48]"),
        Q!("    uzp2            " "v29.4s, v19.4s, v19.4s"),
        Q!("    xtn             " "v4.2s, v19.2d"),
        Q!("    umulh           " "x8, x9, x13"),
        Q!("    rev64           " "v20.4s, v23.4s"),
        Q!("    umull           " "v16.2d, v19.2s, v19.2s"),
        Q!("    umull           " "v1.2d, v29.2s, v4.2s"),
        Q!("    mul             " "v20.4s, v20.4s, v0.4s"),
        Q!("    subs            " "x14, x9, x13"),
        Q!("    umulh           " "x15, x9, x1"),
        Q!("    mov             " "x16, v16.d[1]"),
        Q!("    umull2          " "v4.2d, v19.4s, v19.4s"),
        Q!("    mov             " "x4, v16.d[0]"),
        Q!("    uzp1            " "v17.4s, v23.4s, v0.4s"),
        Q!("    uaddlp          " "v19.2d, v20.4s"),
        Q!("    lsr             " "x7, x8, #63"),
        Q!("    mul             " "x11, x9, x13"),
        Q!("    mov             " "x12, v1.d[0]"),
        Q!("    csetm           " "x5, cc"),
        Q!("    cneg            " "x6, x14, cc"),
        Q!("    mov             " "x3, v4.d[1]"),
        Q!("    mov             " "x14, v4.d[0]"),
        Q!("    subs            " "x2, x10, x1"),
        Q!("    mov             " "x9, v1.d[1]"),
        Q!("    cneg            " "x17, x2, cc"),
        Q!("    cinv            " "x2, x5, cc"),
        Q!("    adds            " "x5, x4, x12, lsl #33"),
        Q!("    extr            " "x4, x8, x11, #63"),
        Q!("    lsr             " "x8, x12, #31"),
        Q!("    uzp1            " "v20.4s, v0.4s, v0.4s"),
        Q!("    shl             " "v19.2d, v19.2d, #32"),
        Q!("    adc             " "x16, x16, x8"),
        Q!("    adds            " "x8, x14, x9, lsl #33"),
        Q!("    lsr             " "x14, x9, #31"),
        Q!("    lsl             " "x9, x5, #32"),
        Q!("    umlal           " "v19.2d, v20.2s, v17.2s"),
        Q!("    adc             " "x14, x3, x14"),
        Q!("    adds            " "x16, x16, x11, lsl #1"),
        Q!("    lsr             " "x3, x5, #32"),
        Q!("    umulh           " "x12, x6, x17"),
        Q!("    adcs            " "x4, x8, x4"),
        Q!("    adc             " "x11, x14, x7"),
        Q!("    subs            " "x8, x5, x9"),
        Q!("    sbc             " "x5, x5, x3"),
        Q!("    adds            " "x16, x16, x9"),
        Q!("    mov             " "x14, v19.d[0]"),
        Q!("    mul             " "x17, x6, x17"),
        Q!("    adcs            " "x3, x4, x3"),
        Q!("    lsl             " "x7, x16, #32"),
        Q!("    umulh           " "x13, x13, x10"),
        Q!("    adcs            " "x11, x11, x8"),
        Q!("    lsr             " "x8, x16, #32"),
        Q!("    adc             " "x5, x5, xzr"),
        Q!("    subs            " "x9, x16, x7"),
        Q!("    sbc             " "x16, x16, x8"),
        Q!("    adds            " "x7, x3, x7"),
        Q!("    mov             " "x3, v19.d[1]"),
        Q!("    adcs            " "x6, x11, x8"),
        Q!("    umulh           " "x11, x1, x10"),
        Q!("    adcs            " "x5, x5, x9"),
        Q!("    eor             " "x8, x12, x2"),
        Q!("    adc             " "x9, x16, xzr"),
        Q!("    adds            " "x16, x14, x15"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x12, x16, x3"),
        Q!("    eor             " "x16, x17, x2"),
        Q!("    mul             " "x4, x1, x10"),
        Q!("    adcs            " "x15, x15, x13"),
        Q!("    adc             " "x17, x13, xzr"),
        Q!("    adds            " "x15, x15, x3"),
        Q!("    adc             " "x3, x17, xzr"),
        Q!("    cmn             " "x2, #0x1"),
        Q!("    mul             " "x17, x10, x10"),
        Q!("    adcs            " "x12, x12, x16"),
        Q!("    adcs            " "x16, x15, x8"),
        Q!("    umulh           " "x10, x10, x10"),
        Q!("    adc             " "x2, x3, x2"),
        Q!("    adds            " "x14, x14, x14"),
        Q!("    adcs            " "x12, x12, x12"),
        Q!("    adcs            " "x16, x16, x16"),
        Q!("    adcs            " "x2, x2, x2"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    adds            " "x14, x14, x7"),
        Q!("    mul             " "x3, x1, x1"),
        Q!("    adcs            " "x12, x12, x6"),
        Q!("    lsr             " "x7, x14, #32"),
        Q!("    adcs            " "x16, x16, x5"),
        Q!("    lsl             " "x5, x14, #32"),
        Q!("    umulh           " "x13, x1, x1"),
        Q!("    adcs            " "x2, x2, x9"),
        Q!("    mov             " "x6, #0xffffffff"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x8, x4, x4"),
        Q!("    adcs            " "x1, x11, x11"),
        Q!("    mov             " "x11, #0xffffffff00000001"),
        Q!("    adc             " "x4, xzr, xzr"),
        Q!("    subs            " "x9, x14, x5"),
        Q!("    sbc             " "x14, x14, x7"),
        Q!("    adds            " "x12, x12, x5"),
        Q!("    adcs            " "x16, x16, x7"),
        Q!("    lsl             " "x5, x12, #32"),
        Q!("    lsr             " "x7, x12, #32"),
        Q!("    adcs            " "x2, x2, x9"),
        Q!("    adcs            " "x14, x15, x14"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    subs            " "x9, x12, x5"),
        Q!("    sbc             " "x12, x12, x7"),
        Q!("    adds            " "x16, x16, x5"),
        Q!("    adcs            " "x2, x2, x7"),
        Q!("    adcs            " "x14, x14, x9"),
        Q!("    adcs            " "x12, x15, x12"),
        Q!("    adc             " "x15, xzr, xzr"),
        Q!("    adds            " "x16, x16, x3"),
        Q!("    adcs            " "x2, x2, x13"),
        Q!("    adcs            " "x14, x14, x17"),
        Q!("    adcs            " "x12, x12, x10"),
        Q!("    adc             " "x15, x15, xzr"),
        Q!("    adds            " "x2, x2, x8"),
        Q!("    adcs            " "x14, x14, x1"),
        Q!("    adcs            " "x12, x12, x4"),
        Q!("    adcs            " "x15, x15, xzr"),
        Q!("    adds            " "x3, x16, #0x1"),
        Q!("    sbcs            " "x5, x2, x6"),
        Q!("    sbcs            " "x8, x14, xzr"),
        Q!("    sbcs            " "x11, x12, x11"),
        Q!("    sbcs            " "xzr, x15, xzr"),
        Q!("    csel            " "x24, x3, x16, cs"),
        Q!("    csel            " "x25, x8, x14, cs"),
        Q!("    csel            " "x26, x11, x12, cs"),
        Q!("    csel            " "x27, x5, x2, cs"),
        Q!("    stp             " "x25, x26, [x0, #16]"),
        Q!("    stp             " "x24, x27, [x0]"),
        Q!("    ldr             " "q20, [sp, #96]"),
        Q!("    ldr             " "q0, [sp, #160]"),
        Q!("    ldp             " "x6, x10, [sp, #96]"),
        Q!("    rev64           " "v16.4s, v20.4s"),
        Q!("    subs            " "x4, x20, x21"),
        Q!("    csetm           " "x3, cc"),
        Q!("    cneg            " "x13, x4, cc"),
        Q!("    mul             " "v16.4s, v16.4s, v0.4s"),
        Q!("    umulh           " "x12, x21, x10"),
        Q!("    uzp1            " "v28.4s, v20.4s, v0.4s"),
        Q!("    subs            " "x14, x22, x20"),
        Q!("    ldr             " "q20, [sp, #112]"),
        Q!("    sbcs            " "x5, x23, x21"),
        Q!("    ngc             " "x17, xzr"),
        Q!("    subs            " "x8, x22, x23"),
        Q!("    uaddlp          " "v27.2d, v16.4s"),
        Q!("    umulh           " "x4, x20, x6"),
        Q!("    uzp1            " "v21.4s, v0.4s, v0.4s"),
        Q!("    cneg            " "x11, x8, cc"),
        Q!("    shl             " "v17.2d, v27.2d, #32"),
        Q!("    csetm           " "x15, cc"),
        Q!("    subs            " "x9, x10, x6"),
        Q!("    eor             " "x7, x14, x17"),
        Q!("    umlal           " "v17.2d, v21.2s, v28.2s"),
        Q!("    cneg            " "x8, x9, cc"),
        Q!("    cinv            " "x9, x3, cc"),
        Q!("    cmn             " "x17, #0x1"),
        Q!("    ldr             " "q28, [sp, #176]"),
        Q!("    adcs            " "x14, x7, xzr"),
        Q!("    mul             " "x7, x13, x8"),
        Q!("    eor             " "x1, x5, x17"),
        Q!("    adcs            " "x5, x1, xzr"),
        Q!("    xtn             " "v1.2s, v20.2d"),
        Q!("    mov             " "x1, v17.d[0]"),
        Q!("    mov             " "x3, v17.d[1]"),
        Q!("    uzp2            " "v16.4s, v20.4s, v20.4s"),
        Q!("    umulh           " "x16, x13, x8"),
        Q!("    eor             " "x13, x7, x9"),
        Q!("    adds            " "x8, x1, x3"),
        Q!("    adcs            " "x7, x4, x12"),
        Q!("    xtn             " "v0.2s, v28.2d"),
        Q!("    adcs            " "x12, x12, xzr"),
        Q!("    adds            " "x8, x4, x8"),
        Q!("    adcs            " "x3, x3, x7"),
        Q!("    ldp             " "x7, x2, [sp, #112]"),
        Q!("    adcs            " "x12, x12, xzr"),
        Q!("    cmn             " "x9, #0x1"),
        Q!("    adcs            " "x8, x8, x13"),
        Q!("    eor             " "x13, x16, x9"),
        Q!("    adcs            " "x16, x3, x13"),
        Q!("    lsl             " "x3, x1, #32"),
        Q!("    adc             " "x13, x12, x9"),
        Q!("    subs            " "x12, x6, x7"),
        Q!("    sbcs            " "x9, x10, x2"),
        Q!("    lsr             " "x10, x1, #32"),
        Q!("    ngc             " "x4, xzr"),
        Q!("    subs            " "x6, x2, x7"),
        Q!("    cinv            " "x2, x15, cc"),
        Q!("    cneg            " "x6, x6, cc"),
        Q!("    subs            " "x7, x1, x3"),
        Q!("    eor             " "x9, x9, x4"),
        Q!("    sbc             " "x1, x1, x10"),
        Q!("    adds            " "x15, x8, x3"),
        Q!("    adcs            " "x3, x16, x10"),
        Q!("    mul             " "x16, x11, x6"),
        Q!("    adcs            " "x8, x13, x7"),
        Q!("    eor             " "x13, x12, x4"),
        Q!("    adc             " "x10, x1, xzr"),
        Q!("    cmn             " "x4, #0x1"),
        Q!("    umulh           " "x6, x11, x6"),
        Q!("    adcs            " "x11, x13, xzr"),
        Q!("    adcs            " "x1, x9, xzr"),
        Q!("    lsl             " "x13, x15, #32"),
        Q!("    subs            " "x12, x15, x13"),
        Q!("    lsr             " "x7, x15, #32"),
        Q!("    sbc             " "x15, x15, x7"),
        Q!("    adds            " "x20, x3, x13"),
        Q!("    adcs            " "x21, x8, x7"),
        Q!("    umulh           " "x8, x14, x11"),
        Q!("    umull           " "v21.2d, v0.2s, v1.2s"),
        Q!("    adcs            " "x22, x10, x12"),
        Q!("    umull           " "v3.2d, v0.2s, v16.2s"),
        Q!("    adc             " "x23, x15, xzr"),
        Q!("    rev64           " "v24.4s, v20.4s"),
        Q!("    movi            " "v2.2d, #0xffffffff"),
        Q!("    mul             " "x10, x14, x11"),
        Q!("    mul             " "v4.4s, v24.4s, v28.4s"),
        Q!("    subs            " "x13, x14, x5"),
        Q!("    uzp2            " "v19.4s, v28.4s, v28.4s"),
        Q!("    csetm           " "x15, cc"),
        Q!("    usra            " "v3.2d, v21.2d, #32"),
        Q!("    mul             " "x7, x5, x1"),
        Q!("    umull           " "v21.2d, v19.2s, v16.2s"),
        Q!("    cneg            " "x13, x13, cc"),
        Q!("    uaddlp          " "v5.2d, v4.4s"),
        Q!("    subs            " "x11, x1, x11"),
        Q!("    and             " "v16.16b, v3.16b, v2.16b"),
        Q!("    umulh           " "x5, x5, x1"),
        Q!("    shl             " "v24.2d, v5.2d, #32"),
        Q!("    cneg            " "x11, x11, cc"),
        Q!("    umlal           " "v16.2d, v19.2s, v1.2s"),
        Q!("    cinv            " "x12, x15, cc"),
        Q!("    umlal           " "v24.2d, v0.2s, v1.2s"),
        Q!("    adds            " "x15, x10, x7"),
        Q!("    mul             " "x14, x13, x11"),
        Q!("    eor             " "x1, x6, x2"),
        Q!("    adcs            " "x6, x8, x5"),
        Q!("    usra            " "v21.2d, v3.2d, #32"),
        Q!("    adcs            " "x9, x5, xzr"),
        Q!("    umulh           " "x11, x13, x11"),
        Q!("    adds            " "x15, x8, x15"),
        Q!("    adcs            " "x7, x7, x6"),
        Q!("    eor             " "x8, x14, x12"),
        Q!("    usra            " "v21.2d, v16.2d, #32"),
        Q!("    adcs            " "x13, x9, xzr"),
        Q!("    cmn             " "x12, #0x1"),
        Q!("    mov             " "x9, v24.d[1]"),
        Q!("    adcs            " "x14, x15, x8"),
        Q!("    eor             " "x6, x11, x12"),
        Q!("    adcs            " "x6, x7, x6"),
        Q!("    mov             " "x5, v24.d[0]"),
        Q!("    mov             " "x11, v21.d[1]"),
        Q!("    mov             " "x7, v21.d[0]"),
        Q!("    adc             " "x3, x13, x12"),
        Q!("    adds            " "x12, x5, x9"),
        Q!("    adcs            " "x13, x7, x11"),
        Q!("    adcs            " "x11, x11, xzr"),
        Q!("    adds            " "x12, x7, x12"),
        Q!("    eor             " "x16, x16, x2"),
        Q!("    adcs            " "x7, x9, x13"),
        Q!("    adcs            " "x11, x11, xzr"),
        Q!("    cmn             " "x2, #0x1"),
        Q!("    adcs            " "x16, x12, x16"),
        Q!("    adcs            " "x1, x7, x1"),
        Q!("    adc             " "x2, x11, x2"),
        Q!("    adds            " "x7, x5, x20"),
        Q!("    adcs            " "x15, x16, x21"),
        Q!("    eor             " "x5, x17, x4"),
        Q!("    adcs            " "x9, x1, x22"),
        Q!("    eor             " "x1, x10, x5"),
        Q!("    adcs            " "x16, x2, x23"),
        Q!("    adc             " "x2, xzr, xzr"),
        Q!("    cmn             " "x5, #0x1"),
        Q!("    eor             " "x13, x14, x5"),
        Q!("    adcs            " "x14, x1, x7"),
        Q!("    eor             " "x1, x6, x5"),
        Q!("    adcs            " "x6, x13, x15"),
        Q!("    adcs            " "x10, x1, x9"),
        Q!("    eor             " "x4, x3, x5"),
        Q!("    mov             " "x1, #0xffffffff"),
        Q!("    adcs            " "x8, x4, x16"),
        Q!("    lsr             " "x13, x14, #32"),
        Q!("    adcs            " "x17, x2, x5"),
        Q!("    adcs            " "x11, x5, xzr"),
        Q!("    adc             " "x4, x5, xzr"),
        Q!("    adds            " "x12, x10, x7"),
        Q!("    adcs            " "x7, x8, x15"),
        Q!("    adcs            " "x5, x17, x9"),
        Q!("    adcs            " "x9, x11, x16"),
        Q!("    lsl             " "x11, x14, #32"),
        Q!("    adc             " "x10, x4, x2"),
        Q!("    subs            " "x17, x14, x11"),
        Q!("    sbc             " "x4, x14, x13"),
        Q!("    adds            " "x11, x6, x11"),
        Q!("    adcs            " "x12, x12, x13"),
        Q!("    lsl             " "x15, x11, #32"),
        Q!("    adcs            " "x17, x7, x17"),
        Q!("    lsr             " "x7, x11, #32"),
        Q!("    adc             " "x13, x4, xzr"),
        Q!("    subs            " "x4, x11, x15"),
        Q!("    sbc             " "x11, x11, x7"),
        Q!("    adds            " "x8, x12, x15"),
        Q!("    adcs            " "x15, x17, x7"),
        Q!("    adcs            " "x4, x13, x4"),
        Q!("    adc             " "x11, x11, xzr"),
        Q!("    adds            " "x7, x5, x4"),
        Q!("    adcs            " "x17, x9, x11"),
        Q!("    adc             " "x13, x10, xzr"),
        Q!("    add             " "x12, x13, #0x1"),
        Q!("    neg             " "x11, x12"),
        Q!("    lsl             " "x4, x12, #32"),
        Q!("    adds            " "x17, x17, x4"),
        Q!("    sub             " "x4, x4, #0x1"),
        Q!("    adc             " "x13, x13, xzr"),
        Q!("    subs            " "x11, x8, x11"),
        Q!("    sbcs            " "x4, x15, x4"),
        Q!("    sbcs            " "x7, x7, xzr"),
        Q!("    sbcs            " "x17, x17, x12"),
        Q!("    sbcs            " "x13, x13, x12"),
        Q!("    mov             " "x12, #0xffffffff00000001"),
        Q!("    adds            " "x14, x11, x13"),
        Q!("    and             " "x1, x1, x13"),
        Q!("    adcs            " "x15, x4, x1"),
        Q!("    and             " "x1, x12, x13"),
        Q!("    stp             " "x14, x15, [sp, #96]"),
        Q!("    adcs            " "x13, x7, xzr"),
        Q!("    adc             " "x20, x17, x1"),
        Q!("    stp             " "x13, x20, [sp, #112]"),
        Q!("    ldp             " "x5, x6, [sp, #64]"),
        Q!("    ldp             " "x4, x3, [sp, #32]"),
        Q!("    subs            " "x5, x5, x4"),
        Q!("    sbcs            " "x6, x6, x3"),
        Q!("    ldp             " "x7, x8, [sp, #80]"),
        Q!("    ldp             " "x4, x3, [sp, #48]"),
        Q!("    sbcs            " "x7, x7, x4"),
        Q!("    sbcs            " "x8, x8, x3"),
        Q!("    csetm           " "x3, cc"),
        Q!("    adds            " "x5, x5, x3"),
        Q!("    and             " "x4, x3, #0xffffffff"),
        Q!("    adcs            " "x6, x6, x4"),
        Q!("    adcs            " "x7, x7, xzr"),
        Q!("    and             " "x4, x3, #0xffffffff00000001"),
        Q!("    adc             " "x8, x8, x4"),
        Q!("    stp             " "x5, x6, [x19, #64]"),
        Q!("    stp             " "x7, x8, [x19, #80]"),
        Q!("    ldp             " "x1, x2, [sp, #128]"),
        Q!("    lsl             " "x0, x1, #2"),
        Q!("    ldp             " "x6, x7, [sp, #160]"),
        Q!("    subs            " "x0, x0, x6"),
        Q!("    extr            " "x1, x2, x1, #62"),
        Q!("    sbcs            " "x1, x1, x7"),
        Q!("    ldp             " "x3, x4, [sp, #144]"),
        Q!("    extr            " "x2, x3, x2, #62"),
        Q!("    ldp             " "x6, x7, [sp, #176]"),
        Q!("    sbcs            " "x2, x2, x6"),
        Q!("    extr            " "x3, x4, x3, #62"),
        Q!("    sbcs            " "x3, x3, x7"),
        Q!("    lsr             " "x4, x4, #62"),
        Q!("    sbc             " "x4, x4, xzr"),
        Q!("    add             " "x5, x4, #0x1"),
        Q!("    lsl             " "x8, x5, #32"),
        Q!("    negs            " "x6, x8"),
        Q!("    ngcs            " "x7, xzr"),
        Q!("    sbc             " "x8, x8, x5"),
        Q!("    adds            " "x0, x0, x5"),
        Q!("    adcs            " "x1, x1, x6"),
        Q!("    adcs            " "x2, x2, x7"),
        Q!("    adcs            " "x3, x3, x8"),
        Q!("    csetm           " "x5, cc"),
        Q!("    adds            " "x0, x0, x5"),
        Q!("    and             " "x6, x5, #0xffffffff"),
        Q!("    adcs            " "x1, x1, x6"),
        Q!("    adcs            " "x2, x2, xzr"),
        Q!("    neg             " "x7, x6"),
        Q!("    adc             " "x3, x3, x7"),
        Q!("    stp             " "x0, x1, [x19]"),
        Q!("    stp             " "x2, x3, [x19, #16]"),
        Q!("    mov             " "x2, #0xffffffffffffffff"),
        Q!("    subs            " "x9, x2, x24"),
        Q!("    mov             " "x2, #0xffffffff"),
        Q!("    sbcs            " "x10, x2, x27"),
        Q!("    ngcs            " "x11, x25"),
        Q!("    mov             " "x2, #0xffffffff00000001"),
        Q!("    sbc             " "x12, x2, x26"),
        Q!("    lsl             " "x3, x9, #3"),
        Q!("    extr            " "x4, x10, x9, #61"),
        Q!("    extr            " "x5, x11, x10, #61"),
        Q!("    extr            " "x6, x12, x11, #61"),
        Q!("    lsr             " "x7, x12, #61"),
        Q!("    mov             " "x1, #0x3"),
        Q!("    mul             " "x8, x14, x1"),
        Q!("    umulh           " "x9, x14, x1"),
        Q!("    adds            " "x3, x3, x8"),
        Q!("    mul             " "x8, x15, x1"),
        Q!("    umulh           " "x10, x15, x1"),
        Q!("    adcs            " "x4, x4, x8"),
        Q!("    mul             " "x8, x13, x1"),
        Q!("    umulh           " "x11, x13, x1"),
        Q!("    adcs            " "x5, x5, x8"),
        Q!("    mul             " "x8, x20, x1"),
        Q!("    umulh           " "x12, x20, x1"),
        Q!("    adcs            " "x6, x6, x8"),
        Q!("    adc             " "x7, x7, xzr"),
        Q!("    adds            " "x4, x4, x9"),
        Q!("    adcs            " "x5, x5, x10"),
        Q!("    adcs            " "x6, x6, x11"),
        Q!("    adc             " "x7, x7, x12"),
        Q!("    add             " "x8, x7, #0x1"),
        Q!("    lsl             " "x10, x8, #32"),
        Q!("    adds            " "x6, x6, x10"),
        Q!("    adc             " "x7, x7, xzr"),
        Q!("    neg             " "x9, x8"),
        Q!("    sub             " "x10, x10, #0x1"),
        Q!("    subs            " "x3, x3, x9"),
        Q!("    sbcs            " "x4, x4, x10"),
        Q!("    sbcs            " "x5, x5, xzr"),
        Q!("    sbcs            " "x6, x6, x8"),
        Q!("    sbc             " "x8, x7, x8"),
        Q!("    adds            " "x3, x3, x8"),
        Q!("    and             " "x9, x8, #0xffffffff"),
        Q!("    adcs            " "x4, x4, x9"),
        Q!("    adcs            " "x5, x5, xzr"),
        Q!("    neg             " "x10, x9"),
        Q!("    adc             " "x6, x6, x10"),
        Q!("    stp             " "x3, x4, [x19, #32]"),
        Q!("    stp             " "x5, x6, [x19, #48]"),

        Q!("    ldp             " "x27, xzr, [sp, " NSPACE!() "+ 64]"),
        Q!("    ldp             " "x25, x26, [sp, " NSPACE!() "+ 48]"),
        Q!("    ldp             " "x23, x24, [sp, " NSPACE!() "+ 32]"),
        Q!("    ldp             " "x21, x22, [sp, " NSPACE!() "+ 16]"),
        Q!("    ldp             " "x19, x20, [sp, " NSPACE!() "]"),
        Q!("    add             " "sp, sp, " NSPACE!() "+ 80"),
        inout("x0") p3.as_mut_ptr() => _,
        inout("x1") p1.as_ptr() => _,
        // clobbers
        out("v0") _,
        out("v19") _,
        out("v20") _,
        out("v23") _,
        out("v28") _,
        out("x10") _,
        out("x11") _,
        out("x12") _,
        out("x13") _,
        out("x14") _,
        out("x15") _,
        out("x16") _,
        out("x17") _,
        out("x2") _,
        out("x20") _,
        out("x21") _,
        out("x22") _,
        out("x23") _,
        out("x24") _,
        out("x25") _,
        out("x26") _,
        out("x27") _,
        out("x3") _,
        out("x4") _,
        out("x5") _,
        out("x6") _,
        out("x7") _,
        out("x8") _,
        out("x9") _,
            )
    };
}
