#!/bin/sh
set -e

export VALGRIND_BUG_494162=1
export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER="valgrind --track-origins=yes"
export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUNNER="valgrind --track-origins=yes"

cargo test --lib --test wycheproof --features __ctgrind "$@"
